apiVersion: v1
data:
    CLIENT_ID: ENC[AES256_GCM,data:NYMQ99PZajezVvMFtXuxnPlFk5Bel47DI2RNn2u5+/Q=,iv:EIrQbxt1MTTpOribueUgLdnA+0NFHFH5hawMVM1i9lo=,tag:YnexBETX3bijgOs0r0hT4A==,type:str]
    CLIENT_SECRET: ENC[AES256_GCM,data:IRia3i0/NntqCQ54LaRmP9AlsaJhnYw24ykB5UANHmKqsrf0JTmAMg==,iv:pRlxwemIgC7nuPLK7dX/eo/9KpN9DiuhjALXQXyW9gE=,tag:JW2Xo5kE8QbFDeTLEWCSxQ==,type:str]
    GITHUB_CLIENT_ID: ENC[AES256_GCM,data:ZWcpxLMBizzePGpQyeVrulYOKD6YYpCxv06QMA==,iv:RLwddQACfAHRjf1gKEgRp1s2xsAUG6IqfdvMw8hEqOo=,tag:V0aSJKcDqYrBINr7Gyrwog==,type:str]
    GITHUB_CLIENT_SECRET: ENC[AES256_GCM,data:7YXwCsonNnD0Pkbzk+FMF3NHfBnxi58ICOWm7lgBgfCIwr+5uOe2uAgFb/StcjV2c3NUcJOUZ8w=,iv:6Drklv4KDxIdCkaQ1MkOEEsFcf/WiwsmyT5fL1L3Wtw=,tag:uXvJpzE/aXh0OOMpq9yZng==,type:str]
    LEAF_K8S_CLIENT_ID: ENC[AES256_GCM,data:qsqIPgIQdvEn8qP+h8klirNVVhdy3spQQx0Otw==,iv:jruyG0tJlnUENGSyJWebArh64bCApykE6bLPtP2UOyg=,tag:SzUz3Y56fwDACwt6MUM3Xg==,type:str]
    LEAF_K8S_CLIENT_SECRET: ENC[AES256_GCM,data:SrzSerlYgjhFa9ve23suCag32RMuR/3/De6Nwh6p,iv:wlyZ4reGiIq3/jeD82R0YQB+FVGWvfXVwof4KZvXg34=,tag:HLHD6lTq/5mq+Emz3Y/5Uw==,type:str]
kind: Secret
metadata:
    creationTimestamp: "2022-08-01T19:10:19Z"
    labels:
        kustomize.toolkit.fluxcd.io/name: dex-secrets
        kustomize.toolkit.fluxcd.io/namespace: dex
    name: dex-auth
    namespace: dex
    resourceVersion: "100574320"
    uid: 934a33b3-05a9-4b1c-b9aa-3941ee8a956c
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-11-18T20:55:46Z"
    mac: ENC[AES256_GCM,data:4rI8bHsncIgHcAkQ+hRwBvo8MYAdy6aClK2wUH0LfcdgHo9Yy4R1Z3LI/BaQiQKmEED0ObzS7bvre1nhsZ8A0i5iKuExdbTkyAJFRsGACd4hjbxgXwbkKCRDxUW0BdZrsTit3Dm0TPamM7hGbBssnNXlGYqt5zIqXiY0ki5Ks74=,iv:E36gcQrS45FW4iULwFtozLe8EtLc5wG1qo9dvmZc7f8=,tag:zXHJ3DOx3sxIFw5BmtnWNw==,type:str]
    pgp:
        - created_at: "2022-11-18T20:55:45Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA2IWPpjKSDN/AQ/9HPB2evkeiXJEDleXBae6Gc/fpDvB4mmG2BK4VDqU/7kv
            2TZlsU1zsarwkvIzSYlKtBZYRZphdkU8r2FHGKBZpkA2OLNxaM2lk9DD35wU3cBI
            onPu3ueMSsGGK4Z0IsohLend0x3iZb5zf/1jRG6aittenmKkLZxrB8gLfhcL0m50
            H3CKgQiTsW9Lt/a1q6QGGVKsGLAEu9GJ4d0SmkpIid0RxQITnsJ7ovFrhJ4r+ZHe
            KwUBPuYFaWmtU6zfqVethiT+tdpcI3xQ0MppYp3btgzAUiI5SOC7DstxlKVIzigq
            APmTnN10WM8af8DbIDa4l6V6EluHjLVq64u97HkwJsBSEzt6UMygcukE31pVNaPm
            bzyX35M89CRM3JHHTkBAdFemL+MGA2BRUZXNqbk7FvPAv7/p2a5taiCIb1YpaUYo
            uHsstxFtAQGOXYwVaUM6fDONsXVUbpanLfErWUnj8W062DsdvSiLIcIRcqTckxUz
            bw/AABr3YXuQ0kdOGDG6PWP7uatkFphK2noRUZ5OFBhjNxQ0Xj1WTgCbEnxclW/n
            kmFTz4uew11sqj6RTvVomlsR2PibOIPSSKDNphJL9zkzPXjpbfK/2Qcmk38d/5Vd
            +gBB3Qd19AMcvaYw+acgdNwnUcQRq8PIfWKLex8gVhBvg837V9xk/RUQJju+gb/U
            aAEJAhCoPYGvzQpFQ1dGikc+6msr2tSMI/kHbsdWgYmqjY0LnGY4ne8NogD7unW9
            BFM1ZBkOjPvtkI/jxtaRot8ILKdmRsQIxOLpKEmH0DQz3yBUuNXNmwveWcrAOTCL
            DUBaXmqgUuuP
            =AOnq
            -----END PGP MESSAGE-----
          fp: 3C778F802D79787BCE9D795CE20F63D488FC275F
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
