apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AWSClusterRoleIdentity
metadata:
  name: "{{ .Values.awsAccountName }}-account-role"
spec:
  allowedNamespaces: {}
  roleARN: "arn:aws:iam::{{ .Values.awsAccountId }}:role/wge-{{ .Values.environment }}-{{ .Values.awsAccountName }}-control-plane"
  sessionName: filecoin-dev-role-session
  sourceidentityRef:
    kind: AWSClusterControllerIdentity
    name: default
