apiVersion: iam.aws.crossplane.io/v1alpha1
kind: InstanceProfile
metadata:
  name: wge-{{ .Values.environment }}-{{ .Values.awsAccountName }}-node-instance-profile
  # annotations:
  #   crossplane.io/external-name: "arn:aws:iam::407967248065:role/${CLUSTER_NAME}-external-dns"
spec:
  providerConfigRef:
    name: {{ .Values.awsAccountName }}-provider
  forProvider:
    roleRef:
     name: wge-{{ .Values.environment }}-{{ .Values.awsAccountName }}-node



