apiVersion: iam.aws.crossplane.io/v1beta1
kind: Role
metadata:
  name: wge-{{ .Values.environment }}-{{ .Values.awsAccountName }}-node
  # annotations:
  #   crossplane.io/external-name: "arn:aws:iam::407967248065:role/${CLUSTER_NAME}-external-dns"
spec:
  providerConfigRef:
    name: {{ .Values.awsAccountName }}-provider
  forProvider:
    assumeRolePolicyDocument: |
      {
      	"Version": "2012-10-17",
      	"Statement": [
      		{
      			"Sid": "",
      			"Effect": "Allow",
      			"Principal": {
      				"Service": "ec2.amazonaws.com"
      			},
      			"Action": [
      				"sts:TagSession",
      				"sts:SetSourceIdentity",
      				"sts:AssumeRole"
      			]
      		}
      	]
      }
