apiVersion: iam.aws.crossplane.io/v1beta1
kind: Policy
metadata:
  name: {{ .Values.awsAccountName }}-nodes
  # annotations:
  #   crossplane.io/external-name: "arn:aws:iam::407967248065:policy/${CLUSTER_NAME}-external-dns"
spec:
  providerConfigRef:
    name: {{ .Values.awsAccountName }}-provider
  deletionPolicy: Delete
  forProvider:
    description: "For the Kubernetes Cloud Provider AWS Control Plane"
    name: wge-{{ .Values.environment }}-nodes.cluster-api-provider-aws.sigs.k8s.io
    document: |
      {
          "Version": "2012-10-17",
          "Statement": [
              {
                  "Action": [
                      "ec2:DescribeInstances",
                      "ec2:DescribeRegions",
                      "ecr:GetAuthorizationToken",
                      "ecr:BatchCheckLayerAvailability",
                      "ecr:GetDownloadUrlForLayer",
                      "ecr:GetRepositoryPolicy",
                      "ecr:DescribeRepositories",
                      "ecr:ListImages",
                      "ecr:BatchGetImage"
                  ],
                  "Resource": [
                      "*"
                  ],
                  "Effect": "Allow"
              },
              {
                  "Action": [
                      "secretsmanager:DeleteSecret",
                      "secretsmanager:GetSecretValue"
                  ],
                  "Resource": [
                      "arn:*:secretsmanager:*:*:secret:aws.cluster.x-k8s.io/*"
                  ],
                  "Effect": "Allow"
              },
              {
                  "Action": [
                      "ssm:UpdateInstanceInformation",
                      "ssmmessages:CreateControlChannel",
                      "ssmmessages:CreateDataChannel",
                      "ssmmessages:OpenControlChannel",
                      "ssmmessages:OpenDataChannel",
                      "s3:GetEncryptionConfiguration"
                  ],
                  "Resource": [
                      "*"
                  ],
                  "Effect": "Allow"
              }
          ]
      }
