apiVersion: aws.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: {{ .Values.awsAccountName }}-provider
spec:
  # VERSION: provider-aws:v0.26.1
  # assumeRole:
  #   roleARN: "arn:aws:iam::407967248065:role/gitops_crossplane_role"
  #   externalID: {{ .Values.awsAccountName }}-crossplane-eks
  # credentials:
  #   source: InjectedIdentity
  assumeRoleARN: "arn:aws:iam::{{ .Values.awsAccountId }}:role/wge-{{ .Values.environment }}_gitops_crossplane_role"
  externalID: netops-crossplane-eks
  credentials:
    source: InjectedIdentity
