apiVersion: v1
stringData:
    netops-alerts-test: ENC[AES256_GCM,data:rsxfR4Nue7YXjNq20rhT30fxC5oTal3RcB1Vlnny/xJZOBp1mwQW9hq2pSmpu2hV8J9VU+uNedqvITlAjhDz1abdf4zcN2NtjLBIV1s=,iv:kozueEoetiwUDx+OAuSabi7MyI1o+b6B/Cyg/ihps4s=,tag:Vwbq4ZGzSEgEAKLU4SZqOg==,type:str]
    fil-infra-alerts: ENC[AES256_GCM,data:xDoZ/ugVE86yyQAFD0X6H/rf3VliKnFfrgcCRQnVAHP1djGEzjOaSjwAJnY5awgZxy2xBbqOddN5YSBgsftoiRjO7SzjfJl7gGSWJCB/SQ==,iv:eQPrzCTILX1MsV7Hg0PZNAg4GjGEUeg+0+1Uupn7kHo=,tag:3fSpgqGG8NsbpBMq8q6g1A==,type:str]
    fil-infra-alerts-test: ENC[AES256_GCM,data:OnAXw0++v1eQ4A2wLORi1C66e6XrytF34OgDrYJhDlU530sqO+NzzC43fG23SaGJyy2mtrDnQBR6M2FFZppzBxKN6CquvL1xJ/ip9Q0=,iv:MqLc2u6lg3c09SXrGkEY2iGbLHrKLn8vtJjBFb8/f1M=,tag:KD+98Jw5PluoODMxHDD1cw==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: alertmanager-slack-urls
    namespace: flux-system
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-07-22T12:36:25Z"
    mac: ENC[AES256_GCM,data:+upZNH3mgICJVq0LCoeqgkljg/q/RioakxoYEJTRkJdxeGr40Gu+tjiIVTX2B/7z54fS7GLffkOSm2S5ciE3myt+iFbd/eHXWnXs3tWTY/m/VnswaPOGvUWLQkcWXJyB3wX4FNF6s7UufoKy/in09uWSA85h1PrgD1FlJeho8ZI=,iv:C1nCpUTEh0dAeCwkEt+flKGP9FGM2KBRXTOD9/yfOZI=,tag:bIEaev+SbiqQMgBpwKrP4Q==,type:str]
    pgp:
        - created_at: "2022-07-22T12:36:24Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA2IWPpjKSDN/ARAAsS2D2JMxB28gocjtUs9CcA34W6peAVxZQTW1ysPid9Je
            WSoZljHe0pidgLVmOIu+puavpUZ6a0CKOjLsOjpAfsamE/L+AcOyYieEakiGqWt7
            f4i05nF2rzhhSrrXvM0HguTFfLaYuhD/dp7AM8Elhr2SgkN1QkaTpXKHLI4Rv3w1
            CKkhj7BkWExyxc0/CuZGTAEVkBS49dbYjNYddvRVINRqUDbjR65bVjKYBOFtAJ+L
            4WGMkIToXG2XjfdQh1wI9dIDZoqS7sB7efSbUz6GqX5qrkS4wBVQ4H9gWHmCMCOT
            zIlRAsJtpehEe6VzqkwcF+M0e88iyGWPkyIxHTSp4J7BSqVe6osF08fdOHOvj3ne
            mbKaB25kd3p6b8bGFGhL/sRV+oAGpb7xKGPa/3saBuVVuGkDWNEtr3vrzPly+QlG
            zjuQE57Zn0Z/XiujbagraY+2U9//LtKEbCRNCbrWV8llB9zeml3V9RPRVVfb/lOQ
            eumiRzTiql2465ekopuqjg4PCsxifeyYJeu7wvIJaDcCn/xp71De9OFx5KbWrH71
            lbbMVYMs/8zWVVx/5GILn1N8dlEuYmbh+4Swpaxic/ECq1YAJALvvzZLhUdBRqnV
            oalRsc8/sQrTk34/7tLTn0hZ+oA2ozWC5ezAuOZF6qfzaPkq3ECjhUUDmfzdya/U
            aAEJAhAlVLO4FxAWRlOTjW5p3hrFD9r31aGt379RMNW3r9RVyO43LTaVIvlzcIcx
            87uBk19cYr9SCoTE912bDLB1+WsqfWv3QApnXDkqo2owiyD85vZZL6K3EU6cCSRg
            ySEerlSGwayj
            =bsSi
            -----END PGP MESSAGE-----
          fp: 3C778F802D79787BCE9D795CE20F63D488FC275F
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
