---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: weave-policy-agent-secrets
  namespace: {{ template "weave-policy-agent.namespace" . }}
  labels:
    {{- include "weave-policy-agent.labels" . | nindent 4 }}   
spec:
  interval: 5m0s
  url: {{ .Values.secrets.url }}
  ref:
    branch: main
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: weave-policy-agent-secrets
  namespace: {{ template "weave-policy-agent.namespace" . }}
  labels:
    {{- include "weave-policy-agent.labels" . | nindent 4 }}   
spec:
  interval: 5m
  {{ if ((.Values.secrets).serviceAccountName) }}
  serviceAccountName: {{ .Values.secrets.serviceAccountName }}
  {{ end }}
  decryption:
    provider: sops
    secretRef:
      name: wge-profiles-sops-gpg
  path: {{ .Values.secrets.path }}
  prune: false
  sourceRef:
    kind: GitRepository
    name: weave-policy-agent-secrets
    namespace: {{ template "weave-policy-agent.namespace" . }}
  timeout: 2m