{{ if ((.Values.secrets).create) }}
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: {{ .Release.Name }}-secrets
  namespace: {{ template "flux-application.namespace" . }}
  labels:
    {{- include "flux-application.labels" . | nindent 4 }}   
spec:
  interval: 5m0s
  url: {{ .Values.secrets.url }}
  {{- if or ((.Values.secrets).branch) ((.Values.secrets).tag) }}
  ref:
    {{- if ((.Values.secrets).branch) }}
    branch: {{ .Values.secrets.branch }}
    {{- end }}
    {{- if ((.Values.secrets).tag) }}
    tag: {{ .Values.secrets.tag }}
    {{- end }}
  {{- end }}
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: {{ .Release.Name }}-secrets
  namespace: {{ template "flux-application.namespace" . }}
  labels:
    {{- include "flux-application.labels" . | nindent 4 }}   
spec:
  interval: 5m
  targetNamespace: {{ .Release.Namespace }}
  {{- if ((.Values.secrets).serviceAccountName) }}
  serviceAccountName: {{ .Values.secrets.serviceAccountName }}
  {{- end }}
  {{- if ((.Values.secrets).key) }}
  decryption:
    provider: sops
    secretRef:
      name: wge-profiles-sops-gpg
  {{- end }}
  path: {{ .Values.secrets.path }}
  prune: true
  sourceRef:
    kind: GitRepository
    name: {{ .Release.Name }}-secrets
    namespace: {{ template "flux-application.namespace" . }}
  timeout: 2m
{{ end }}