apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: flux-application
  namespace: {{ template "flux-application.namespace" . }}
  labels:
    {{- include "flux-application.labels" . | nindent 4 }}   
spec:
  secretRef:
   name: {{ .Values.app.token }}
  interval: 1m0s
  ref:
    branch: {{ .Values.app.branch }}
  timeout: 60s
  url: {{ .Values.app.url }}
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flux-application
  namespace: {{ template "flux-application.namespace" . }}
  labels:
    {{- include "flux-application.labels" . | nindent 4 }}
spec:
  interval: 5m
  {{ if ((.Values.app).serviceAccountName) }}
  serviceAccountName: {{ .Values.app.serviceAccountName }}
  {{ end }}
  {{ if ((.Values.app).key) }}
  decryption:
    provider: sops
    secretRef:
      name:  {{ .Values.app.key }}
  {{ end }}
  path: {{ .Values.app.path }}
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-application
    namespace:  {{ template "flux-application.namespace" . }}
  timeout: 2m