---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: {{ .Release.Name }}-secrets
  namespace: {{ template "flux-application.namespace" . }}
  labels:
    {{- include "flux-application.labels" . | nindent 4 }}   
spec:
  interval: 5m0s
  url: {{ .Values.secrets.url }}
  ref:
    branch: {{ .Values.secrets.branch }}
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: {{ .Release.Name }}-secrets
  namespace: {{ template "flux-application.namespace" . }}
  labels:
    {{- include "flux-application.labels" . | nindent 4 }}   
spec:
  interval: 5m
  {{- if ((.Values.secrets).targetNamespace) }}
  targetNamespace: {{ tpl .Values.secrets.targetNamespace . }}
  {{- end }}
  {{- if ((.Values.secrets).serviceAccountName) }}
  serviceAccountName: {{ .Values.secrets.serviceAccountName }}
  {{- end }}
  {{- if ((.Values.secrets).key) }}
  decryption:
    provider: sops
    secretRef:
      name: wge-profiles-sops-gpg
  {{- end }}
  path: {{ .Values.secrets.path }}
  prune: true
  sourceRef:
    kind: GitRepository
    name: {{ .Release.Name }}-secrets
    namespace: {{ template "flux-application.namespace" . }}
  timeout: 2m