{{ if ((.Values.app).create) }}
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name:  {{ .Release.Name }}-app
  namespace: {{ template "flux-application.namespace" . }}
  labels:
    {{- include "flux-application.labels" . | nindent 4 }}   
spec:
  {{- if ((.Values.app).token) }}
  secretRef:
   name: {{ .Values.app.token }}
  {{- end }}
  interval: 1m0s
  {{- if or ((.Values.app).branch) ((.Values.app).tag) }}
  ref:
  {{- if ((.Values.app).branch) }}
    branch: {{ .Values.app.branch }}
  {{- end }}
  {{- if ((.Values.app).tag) }}
    tag: {{ .Values.app.tag }}
  {{- end }}
  {{- end }}
  timeout: 60s
  url: {{ .Values.app.url }}
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: {{ .Release.Name }}-app
  namespace: {{ template "flux-application.namespace" . }}
  labels:
    {{- include "flux-application.labels" . | nindent 4 }}
spec:
  interval: 5m
  targetNamespace: {{ .Release.Namespace }}
  {{- if ((.Values.app).serviceAccountName) }}
  serviceAccountName: {{ .Values.app.serviceAccountName }}
  {{- end }}
  {{- if ((.Values.app).key) }}
  decryption:
    provider: sops
    secretRef:
      name:  {{ .Values.app.key }}
  {{- end }}
  path: {{ .Values.app.path }}
  prune: true
  sourceRef:
    kind: GitRepository
    name: {{ .Release.Name }}-app
    namespace:  {{ template "flux-application.namespace" . }}
  timeout: 2m
{{ end }}