# This manifest represents a CAPITemplate that will be displayed in the WGE UI
# Management will be in gitops-profile caatalog and the consumed in gitops-root
# All selectable values displayed in the WGE UI to generate a template

template-base:
  flux:
    noCrossNamespaceRefs:
      enabled: false
  kubernetesVersionOptions:
  - "v1.22.6"


  wgePostDeploymentRenderer:
    enabled: true

  namespaceOptions:
  - clusters

  # Name of template
  name: sentinel-template
  description: An AWS EKS template that creates a cluster

  # An array of NodeGroups that are available for selection in the UI
  nodeGroups:
  - name: 0
    type: MachineDeployment   # Only MachineDeployment supported today (Pending MachinePool)
    maxOptions: ["12"]
    minOptions: ["0", "1"]
    availabilityZones: ["a", "b", "c"]
    instanceTypeOptions:
    - "r5.8xlarge"

  regionOptions:
  - "us-east-2"


  # Teams are mapped to DNS values
  teamOptions:
  - "sentinel"


  # AwasAccounts available for selection
  awsAccountOptions:
  - name: test-1
    id: "22222"
  - name: test-2
    id: "33333"


  # valid values "sops" or "kms" (pending support)
  secretsEngine: sops

  requiredProfiles:
  - name: k8s-rbac-permissions
    version: 0.0.8
    editable: true
    values: "\
    adminGroups:\\n
    - org: filecoin-project\\n
    \  team: Sentinel Admin\\n
    - org: filecoin-project\\n
    \  team: Weaveworks\\n
    viewerGroups:\\n
    - org: filecoin-project\\n
    \  team: Sentinel
    "
  - name: external-dns
    version: 0.0.9
    values: "\
    external-dns:\\n
    \ txtOwnerId: {{`{{ .params.CLUSTER_NAME }}`}}\\n
    \ serviceAccount:\\n
    \  annotations:\\n
    \    eks.amazonaws.com/role-arn: arn:aws:iam::{{ template \"template-base.accountIDAnnotation\" . }}:role/{{`{{ .params.CLUSTER_NAME }}`}}-external-dns
    "
  - name: cert-manager
    version: 2.0.1
    values: "\
    cert-manager:\\n
    \ serviceAccount:\\n
    \  annotations:\\n
    \    eks.amazonaws.com/role-arn: arn:aws:iam::{{ template \"template-base.accountIDAnnotation\" . }}:role/{{`{{ .params.CLUSTER_NAME }}`}}-cert-manager
    "
  - name: cert-manager-issuer
    version: 0.0.4
  - name: aws-ebs-csi-driver
    version: 0.0.3
    values: "\
    aws-ebs-csi-driver:\\n
    \ controller:\\n
    \  serviceAccount:\\n
    \   annotations:\\n
    \    eks.amazonaws.com/role-arn: arn:aws:iam::{{ template \"template-base.accountIDAnnotation\" . }}:role/{{`{{ .params.CLUSTER_NAME }}`}}-ebs-csi-driver
    "
  - name: aws-node-term-handler
    version: 0.0.1
  - name: aws-load-balancer-controller
    version: 0.0.2
    values: "\
    aws-load-balancer-controller:\\n
    \ clusterName: {{`{{ .params.CLUSTER_NAME }}`}}\\n
    \ serviceAccount:\\n
    \  annotations:\\n
    \    eks.amazonaws.com/role-arn: arn:aws:iam::{{ template \"template-base.accountIDAnnotation\" . }}:role/{{`{{ .params.CLUSTER_NAME }}`}}-aws-load-balancer-controller
    "
  - name: prometheus
    version: 1.1.8
    editable: true
    values: "\
    \ kube-prometheus-stack:\\n
    \ prometheus:\\n
    \  prometheusSpec:\\n
    \    externalLabels:\\n
    \      cluster: {{`{{ .params.CLUSTER_NAME }}`}}\\n
    \  serviceAccount:\\n
    \    annotations:\\n
    \      eks.amazonaws.com/role-arn: arn:aws:iam::{{ template \"template-base.accountIDAnnotation\" . }}:role/{{`{{ .params.CLUSTER_NAME }}`}}-monitoring\\n
    \  thanosIngress:\\n
    \    hosts:\\n
    \    - thanos.{{`{{`}} printf {{`\\`}}\"{{`\\\\`}}%.*s{{`\\`}}\" 22 .params.CLUSTER_NAME {{`}}`}}s.{{`{{ .params.TEAM }}`}}.{{`{{ .params.AWS_ACCOUNT_NAME }}`}}.w3ops.net\\n
    \    tls:\\n
    \    - secretName: thanos-sidecar-tls\\n
    \      hosts:\\n
    \      - thanos.{{`{{`}} printf {{`\\`}}\"{{`\\\\`}}%.*s{{`\\`}}\" 22 .params.CLUSTER_NAME {{`}}`}}s.{{`{{ .params.TEAM }}`}}.{{`{{ .params.AWS_ACCOUNT_NAME }}`}}.w3ops.net\\n
    thanos:\\n
    \ compactor:\\n
    \  serviceAccount:\\n
    \    annotations:\\n
    \      eks.amazonaws.com/role-arn: arn:aws:iam::{{ template \"template-base.accountIDAnnotation\" . }}:role/{{`{{ .params.CLUSTER_NAME }}`}}-thanos-compactor\\n
    thanos-bucket-config:\\n
    \ region: {{`{{ .params.AWS_REGION }}`}}\\n
    \ clusterName: {{`{{ .params.CLUSTER_NAME }}`}}
    "
  - name: ingress-nginx
    version: 0.0.12
  - name: policy-agent
    version: 1.0.1
  - name: promtail
    version: 0.0.8
    editable: true
    values: "\
    \ promtail:\\n
    \   config:\\n
    \     lokiAddress: https://logs-prod-us-central1.grafana.net/loki/api/v1/push
    \     basic_auth:
    \       username: ${PROMTAIL_USERNAME}
    \       password: ${PROMTAIL_PASSWORD}
    \     file: |
    \       server:
    \         log_level: {{`{{ .Values.config.logLevel }}`}}
    \         http_listen_port: {{`{{ .Values.config.serverPort }}`}}
    \       clients:
    \         - url: {{`{{ tpl .Values.config.lokiAddress . }}`}}
    \           basic_auth:
    \             username: ${PROMTAIL_USERNAME}
    \             password: ${PROMTAIL_PASSWORD}
    \         {{`{{- with .Values.config.snippets.extraClientConfigs }}`}}
    \         {{`{{- toYaml . | nindent 2 }}`}}
    \         {{`{{- end }}`}}
    \       positions:
    \         filename: /run/promtail/positions.yaml
    \       scrape_configs:
    \         {{ `{{- tpl .Values.config.snippets.scrapeConfigs . | nindent 2 }}` }}
    \         {{ `{{- tpl .Values.config.snippets.extraScrapeConfigs . | nindent 2 }}` }}
    \     snippets:\\n
    \       pipelineStages:\\n
    \       - json:\\n
    \           expressions:\\n
    \             log: null\\n
    \             stream: stream\\n
    \       - json:\\n
    \           expressions:\\n
    \             caller: null\\n
    \             level: null\\n
    \             logger: null\\n
    \             reporter: null\\n
    \             task: null\\n
    \             timestamp: ts\\n
    \           source: log\\n
    \       - timestamp:\\n
    \           format: RFC3339Nano\\n
    \           source: timestamp\\n
    \       - labels:\\n
    \           caller: null\\n
    \           level: null\\n
    \           logger: null\\n
    \           reporter: null\\n
    \           task: null\\n
    \       - output:\\n
    \           source: log\\n
    "
  - name: grafana-agent
    version: 0.0.1
