apiVersion: v2
name: velero
description: A Weaveworks Helm chart for Velero
type: application
version: 0.0.3
kubeVersion: ">=1.16.0-0"
home: https://velero.io/
sources:
  - https://github.com/vmware-tanzu/velero

keywords:
- operator
- backup

annotations:
  "weave.works/profile": velero
  "weave.works/category": backup
  "weave.works/operator": "true"
  "weave.works/layer": layer-1
  "weave.works/links": |
    - name: Chart Sources
      url: https://vmware-tanzu.github.io/helm-charts
    - name: Upstream Project
      url: https://vmware-tanzu.github.io/helm-charts
  "weave.works/profile-ci": |
    - "gke"
    - "kind"

maintainers:
  - name: Weaveworks
    email: support@weave.works

dependencies:
- name: velero
  version: "2.29.5"
  repository: "https://vmware-tanzu.github.io/helm-charts"
