velero:
  configuration:
    backupStorageLocation:
      bucket: ""
    provider: aws
    volumeSnapshotLocation:
      config:
        region: ""
  credentials:
    useSecret: false
  initContainers:
  - name: velero-plugin-for-aws
    image: stevenfraser/velero-plugin-for-aws:0.0.3
    volumeMounts:
    - mountPath: /target
      name: plugins
  serviceAccount:
    server:
      annotations:
        eks.amazonaws.com/role-arn: ""
