apiVersion: v2
name: opentelemetry-logzio
description: A Weaveworks Helm chart for opentelemetry-logzio
type: application
version: 0.0.1
kubeVersion: ">=1.16.0-0"
home: https://github.com/weaveworks/profiles-catalog
sources:
  - https://github.com/open-telemetry/opentelemetry-helm-charts
  - https://github.com/open-telemetry/opentelemetry-logzio
  - https://github.com/open-telemetry/opentelemetry-logzio-contrib/tree/main/exporter/logzioexporter

keywords:
- operator
- opentelemetry-logzio
- observability

annotations:
  "weave.works/category": Observability
  "weave.works/operator": "true"
  "weave.works/layer": layer-2
  "weave.works/links": |
    - name: Chart Sources
      url: https://github.com/open-telemetry/opentelemetry-helm-charts
    - name: Upstream Project
      url: https://github.com/open-telemetry/opentelemetry-collector-config
  "weave.works/profile-ci": |
    - "gke"
    - "kind"


maintainers:
  - name: Weaveworks
    email: support@weave.works

dependencies:
- name: opentelemetry-collector-config
  version: "0.0.1"
  repository: "file://../opentelemetry-collector-config"
