secrets:
  url: https://github.com/filecoin-project/gitops-profile-catalog
  path: "./secrets/opentelemetry-logzio"
  serviceAccountName: kustomize-controller

mode: sidecar
image: otel/opentelemetry-collector-contrib:0.53.0
ports:
- name: otlp
  port: 4317
  protocol: TCP
  targetPort: 4317
- name: jgr-udp-thriftc
  port: 6831
  protocol: UDP
  targetPort: 6831
- name: jgr-udp-thrift
  port: 6832
  protocol: UDP
  targetPort: 6832
- name: jaeger-thrift
  port: 14268
  protocol: TCP
  targetPort: 14268
- name: jaeger-grpc
  port: 14250
  protocol: TCP
  targetPort: 14250
- name: zipkin
  port: 9411
  protocol: TCP
  targetPort: 9411
config: |
  receivers:
    otlp:
      protocols:
        grpc:
        http:
    zipkin:
    jaeger:
      protocols:
        thrift_compact:
          endpoint: "0.0.0.0:6831"
        thrift_binary:
          endpoint: "0.0.0.0:6832"
        grpc:
          endpoint: "0.0.0.0:14250"
        thrift_http:
          endpoint: "0.0.0.0:14268"
  exporters:
    logzio:
      account_token: XSPlRAERPgwdECMwtPmHprpjCPYRGXIF
      
  processors:
    probabilistic_sampler:
      hash_seed: 22
      sampling_percentage: 1
    batch:
      send_batch_size: 1024
      timeout: 10s
  extensions:
    pprof:
      endpoint: :1777
    zpages:
      endpoint: :55679
    health_check:
  service:
    extensions: [health_check, pprof, zpages]
    pipelines:
      traces:
        receivers: [jaeger,otlp,zipkin]
        processors: [batch,probabilistic_sampler]
        exporters: [logzio]