opentelemetry-collector-config:
  secrets:
    url: https://github.com/filecoin-project/gitops-profile-catalog
    path: "./secrets/opentelemetry-logzio"
    serviceAccountName: kustomize-controller
  args:
    set: exporters.logzio.account_token=${API_TOKEN}
  envFrom:
  - secretRef:
      name: logzio-auth
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
      zipkin:
      jaeger:
        protocols:
          thrift_compact:
            endpoint: "0.0.0.0:6831"
          thrift_binary:
            endpoint: "0.0.0.0:6832"
          grpc:
            endpoint: "0.0.0.0:14250"
          thrift_http:
            endpoint: "0.0.0.0:14268"
    exporters:
      logzio:
        account_token: ""
        
    processors:
      probabilistic_sampler:
        hash_seed: 22
        sampling_percentage: 100
      batch:
        send_batch_size: 1024
        timeout: 10s
    extensions:
      pprof:
        endpoint: :1777
      zpages:
        endpoint: :55679
      health_check:
    service:
      extensions: [health_check, pprof, zpages]
      pipelines:
        traces:
          receivers: [jaeger,otlp,zipkin]
          processors: [batch,probabilistic_sampler]
          exporters: [logzio]
