apiVersion: v2
name: template-base
description: A Weaveworks Helm chart for template
type: application
version: 0.2.2
kubeVersion: ">=1.16.0-0"
home: https://github.com/weaveworks/profiles-catalog

keywords:
- template-base

maintainers:
  - name: Weaveworks
    email: support@weave.works
