# This manifest represents a CAPITemplate that will be displayed in the WGE UI
# Management will be in gitops-profile caatalog and the consumed in gitops-root
# All selectable values displayed in the WGE UI to generate a template

# K8s version applied to the leafcluster
kubernetesVersionOptions:
- "v1.22.6"

namespaceOptions:
- clusters

# Name of template
name: template
description: An AWS EKS template that creates a cluster

# An array of NodeGroups that are available for selection in the UI
nodeGroups:
- name: 0
  type: MachineDeployment   # Only MachineDeployment supported today (Pending MachinePool)
  maxOptions: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "15", "25", "30"]
  minOptions: ["0", "1"]
  availabilityZones: ["a", "b", "c"]
  instanceTypeOptions:
  - "t3.large"
  - "t3.xlarge"
  - "m5a.large"
  - "m5a.xlarge"
  - "m5a.2xlarge"
  - "c5a.xlarge"
  - "c5a.2xlarge"
  - "c5a.4xlarge"
  - "t3.2xlarge"
  - "r5.8xlarge"
- name: 1
  type: MachineDeployment   # Only MachineDeployment supported today (Pending MachinePool)
  maxOptions: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "15", "25", "30"]
  minOptions: ["0", "1"]
  availabilityZones: ["a", "b", "c"]
  instanceTypeOptions:
  - "t3.large"
  - "t3.xlarge"
  - "m5a.large"
  - "m5a.xlarge"
  - "m5a.2xlarge"
  - "c5a.xlarge"
  - "c5a.2xlarge"
  - "c5a.4xlarge"
  - "t3.2xlarge"
  - "r5.8xlarge"


regionOptions:
- "us-east-2"
- "us-west-2"
- "eu-west-1"
- "ap-northeast-1"
- "ap-southeast-2"
- "sa-east-1"


# Teams are mapped to DNS values
teamOptions:
- "netops"
- "sti"
- "fil-infra"
- "sentinel"
- "bedrock"


# AwasAccounts available for selection
awsAccountOptions:
- name: test-1
  id: "22222"
- name: test-2
  id: "33333"


# valid values "sops" or "kms" (pending support)
secretsEngine: sops

requiredProfiles:
- name: k8s-rbac-permissions
  version: 0.0.8
  values: 'adminGroups:\n- org: filecoin-project\n  team: bedrock-go\n- org: filecoin-project\n  team: Weaveworks\n- org: filecoin-project\n  team: infra'
- name: external-dns
  version: 0.0.9
- name: cert-manager
  version: 2.0.1
- name: cert-manager-issuer
  version: 0.0.4
- name: ebs-csi-controller
  version: 0.0.2
- name: aws-node-term-handler
  version: 0.0.1
- name: aws-load-balancer-controller
  version: 0.0.2
- name: prometheus
  version: 1.1.8
- name: ingress-nginx
  version: 0.0.12
- name: policy-agent
  version: 0.2.11
- name: promtail
  version: 0.0.5

environment: nonprod
oidcURL: https://nonprod-auth.w3ops.net
