apiVersion: v1
data:
    CLIENT_ID: ENC[AES256_GCM,data:Obi3R7Dx7ZZ3mUzggvXC9VLzLX+5oNm3xPA4urcWoyo=,iv:PavWuBa61dq/vhdGwAJPleED0gjMHFb7KTPP0ZJYed8=,tag:CuIp0+N9SNQEk106fhS1LA==,type:str]
    CLIENT_SECRET: ENC[AES256_GCM,data:MS7ModoLq+1fiohea01HW+H3wukLc7BHo87uk3zX4noIsb01mRnyxA==,iv:Zh9qVCoczs56lUViZ26wt77ztDXcPDmwdy2YMLTgB3c=,tag:yJe3AKSPK1jWqs0CnLCu7w==,type:str]
    GITHUB_CLIENT_ID: ENC[AES256_GCM,data:XiNcKfPIA5Go8Z5JQOYig49NNjVgRZXXmhrdfQ==,iv:kCf5RwHLJtfBa1HgxGZH3vKiU1fszX4UoP3OJxyP7rI=,tag:BxdBNiZwguVkdWJILRwh/w==,type:str]
    GITHUB_CLIENT_SECRET: ENC[AES256_GCM,data:RatZ5c8dFR8RjREQhzS2Rm5260CPr/IO43Gi6yP8D4bFBgcmEaULflBYIMpE3h/sM/6LNXIejAg=,iv:yYLWZ6b9UryVEzeRK4B8Q9vT/XZ6WiX/4MwnxEvgW6Q=,tag:xNm6pL6shPaA4FjhG+4Mng==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: dex-auth
    namespace: wego-system
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-05-04T19:42:56Z"
    mac: ENC[AES256_GCM,data:FzzlM0Rt/cExqoqTwZ5quVfaAPAcT8z+QR37P6cofL4JQEIkHXhM9R3pfPlAOIXVF8BOtv+ESQOTGsKG6gzigwwBxfgJrs3othjFU1J1r5Rya3KIMEed+07o9Tz5iGyVKuKz/CIHITncSNKpTdNj9Qb10Nm+PTCVFRDZcq+hDrA=,iv:H0XxgWsKZBTvAmoi230gxZnuPWdJ+MUS2THgmcsHchU=,tag:MZ3ZZoW42uQZ9iK9OMStBw==,type:str]
    pgp:
        - created_at: "2022-05-04T19:42:55Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA2IWPpjKSDN/AQ//baBika3DtNyGBqRjSEuE2pGyNmdTyGrGcGYFJC0f9Che
            C4p5tKe4Yl+8N3F7qvIuXv0hXnTKzblesQeXiv0e2AioIbpXGaBiI09xzTvhDFBM
            CV+uJgzRsKN75Vov6MQSSRL+aOkmJY8b54UwP50KtYqOWd2qD+iG0A7kkgUFtR7D
            4RFrrZ5wzJ0iSsEPaSdd5P67QyBWngn3JwLxgu4YpxwFK5NNQOslmt95FnOoMKT6
            RkFNYxsBSaXPcaH9zjLzCI7k8js/CwOVBNx0PuKdfmI6+dPfIt+dMv2c6sVi4C0I
            foU0uVw1kBEy4tMxyOr9bjy2iPpGICeSmToBLffE9MgUDV/ZMGaNOhjIMEWD0iv+
            VTUcKdEW3itLPN80aejQGxVzvXT10Y4c9sNG5ANzwfFTyQM1pdDEhQyXKaJFTmC5
            kOFo1vXKc3hubggFv8KWYcU1DhvP3GiQ9JS0RW049jdzLcPRgidGjK5pn6SnhXH2
            vQ3lddaxpK22BRL3pVKFAUaDz5I9aEOypHGI7QLpiYuxc9b7FuHtpG6CFKnyJsEm
            Jl6KC9odt/e0U3jCGa9s5i4+5DHm6PrwSsfut5GdfZjwYIrjQ7+0BsxKQr6KmkLe
            Pg3u9FjGj1br12u8iyyVV6iw+VCMAxYKxcz4ZbiCmi0uN5BL+8Sv9XhZgWsW9t3U
            aAEJAhBY4HM4xJVYvnmgXmbYziVDwsWtkGzDeBr2yY9LXxba8uLRdoLuR0S1TO1f
            rKq0eri8OxnXy8gzGl/Ee4I4C5RH2xCCGKN2LHsXtJYSt9ra0X1d3djCGhsidD2C
            Z5azHPKDjRfh
            =PKe0
            -----END PGP MESSAGE-----
          fp: 3C778F802D79787BCE9D795CE20F63D488FC275F
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
