apiVersion: v1
data:
    clientID: ENC[AES256_GCM,data:0a95iCFuDHd59VAoS1FeXbvld9D+ILteFECeo1ghi/Q=,iv:scKA8wqtHjKkXr0uvysaiaoXamS9IQA6G6Y0VIj3xCU=,tag:IT2WA+I8zo12Zmk7XGtyFA==,type:str]
    clientSecret: ENC[AES256_GCM,data:cZUDuFRaOOZMiicxNyyVZJ4Bhi7YYxVVohJZOS8dtpWQN5kIjzl3FQ==,iv:xmm8yaMOhcKZWNCx8KdKb+EEwzfvZWh2VG9yIEzcAt8=,tag:2zuFxeRvxLGs4rZvXRgtUQ==,type:str]
    issuerURL: ENC[AES256_GCM,data:w2ggXIkEd/j+QC5zWRX56PuRVConzLJbQKYUBGoAdDKh7H7qIi3/1Q==,iv:lycfGwpMZsRXkw50Y0+spqYlSB02flZJM9mubtW/rYA=,tag:4MF2Bb7pZVOufuH2fiA/Yg==,type:str]
    redirectURL: ENC[AES256_GCM,data:li917ymGqOuLTedWnDtpeBReM8RLx6CdyhrX/fiZOQAWBPyUgI3Jmf+e/ZkFc3jQvv0f1m1vY4wgPr12ZWobFQ==,iv:3vqFeTsHKQAmSsL3XDJ0uE1QWUmeJg7HA0GtBkd4izU=,tag:4TWHueMKxeSyaY/HiBPf2w==,type:str]
kind: Secret
metadata:
    name: oidc-auth
    namespace: wego-system
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-05-04T20:08:18Z"
    mac: ENC[AES256_GCM,data:2JRMAnCOnmRVdSE7Tu5rRiLstIx3r1lLR9+AIvoGmIUFc1sWvI3IcKYqYw9hVUCGITcDL1l+acgT0bu3gHT0+wuxPOuentVhPMWz1JLBHuz6yz7VX91X44+zUs7gYD8Ww5/O7XhIKLzqiDsDzAFwI46kJ9iHlgogLTrGZVTgbx8=,iv:7TT0zE9NcdWCIDabzy0eI4a7DNkUKUmr8l25QDqgKbk=,tag:gctfVvsqg2xXIYhtKEJ94A==,type:str]
    pgp:
        - created_at: "2022-05-04T20:08:17Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA2IWPpjKSDN/AQ//f6+EFP7+JGbow0JY23fCuASuc1scIatfZLwR5DThAyJp
            68rBysJdFB5abDmEFRmvskWsGLZEDJiPglpbpWFwyHVK8KwgCphG6RFXFehcp+01
            qDu4T7wSCgDZitZgcmlerXg7CflSxnNi8uJ4XxUl41i0EGpWbEfMX/Y/Xh5PJtmz
            kR3f7l6EwDmJCZLkEeHXEDZdUDhNk/v6l/jaatnbJJuU8WzO0FpR8wW/tEj31m5s
            hHiinsAvuRyxK+Z9DYhWbXOOenvRnAJycko0EOFtWDh+y9x3oEi5BTqbjalr+SZU
            ijOyBrp9r3rZho9Bl6zKsWh6rBz9tHvEhUKIYKDUwAKz8m1pU8PCb1usEgx1LMJo
            kCHDRjXDtKKbSGGzKrHV21bVnu8lgleq4wOdgyEg9aYkdpzwGasXoZTHr0Yp1aG6
            BC3IUItglgfHqPOLKmP6u3+Nvb9eGcYd5NnZGArBWm1Z3k1g1By8m22xn59rTtMz
            PzkPnsRFE2UJooZ6/1h3zRHS8VkpSVTsvEYT5cy4OPithCOnWugQzkuCu+GOpKMZ
            ZnqIqd4BXPbD5i+6ixQlkIZkuNF+SfehjYCFyBAFXu9rgfbrKhBhrRSikfHCoO6t
            aVnoXlpRLa4beluEFoFV1n3fum7R6YiCgSCWHpvrrNZAqPtsgQ5sOW5dn7W9RezU
            aAEJAhAHEpoZUMao4CkjVMDUeDCVQjzvaNThX3384xrYOiEfpLDwFA1ZYBceix3n
            uIlInab4TwKvCVuFl6QLH3tGUcLB9HmWQTB7UX06YzKHS5DX72YhAIrDmgNrnrVu
            OErCXPXgYAQE
            =RIgw
            -----END PGP MESSAGE-----
          fp: 3C778F802D79787BCE9D795CE20F63D488FC275F
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
