tf-controller:
  enabled: true
  replicaCount: 1
  concurrency: 24
  resources:
    limits:
      cpu: 1000m
      memory: 2Gi
    requests:
      cpu: 400m
      memory: 64Mi
  caCertValidityDuration: 24h
  certRotationCheckFrequency: 30m
  image:
    tag: v0.12.0-rc.5
  runner:
    image:
      tag: v0.12.0-rc.5
