secrets:
  url: https://github.com/filecoin-project/gitops-profile-catalog
  path: "./profiles/secrets/prometheus"

kube-prometheus-stack:
  fullnameOverride: weaveworks-prometheus
  enabled: true
  grafana:
    enabled: false
  prometheus:
    prometheusSpec:
      remoteWrite:
      - url: "https://prometheus-us-central1.grafana.net/api/prom/push"
        basicAuth:
          username:
            name: grafana-cloud-secret
            key: username
          password:
            name: grafana-cloud-secret
            key: password
