secrets:
  url: https://github.com/filecoin-project/gitops-profile-catalog
  path: "./secrets/prometheus"
  serviceAccountName: kustomize-controller

# region: '{{ .params.AWS_REGION }}'
# clusterName: '{{ .params.CLUSTER_NAME }}'

kube-prometheus-stack:
  fullnameOverride: weaveworks-prometheus
  enabled: true
  grafana:
    enabled: false
  alertManager:
    enabled: true
    alertmanagerSpec:
      replicas: 3
      volumeMounts:
        - name: alertmanager-tmpl
          mountPath: '/etc/alertmanager/config'
      volumes:
        - name: alertmanager-tmpl
          configMap:
            name: alertmanager-tmpl
    config:
      route:
        group_by: ["alertname", "cluster"]
        group_wait: 500ms
        receiver: "null"
        group_interval: 500ms
        repeat_interval: 1d
      templates:
        - '/etc/alertmanager/config/*.tmpl'

  prometheus:
    prometheusSpec:
      replicaExternalLabelName: __replica__
      thanos:
        objectStorageConfig:
          key: objstore.yml
          name: thanos-storage-config
      retention: 2d
      retentionSize: "15GB"
      ruleSelectorNilUsesHelmValues: false
      serviceMonitorSelectorNilUsesHelmValues: false
      podMonitorSelectorNilUsesHelmValues: false
      storageSpec:
        volumeClaimTemplate:
          spec:
            storageClassName: gp2
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 20Gi
    serviceAccount:
      annotations:
        eks.amazonaws.com/role-arn: 'arn:aws:iam::{{ .params.AWS_ACCOUNT_ID }}:role/{{ .params.CLUSTER_NAME }}-monitoring'
    thanosIngress:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt"
        nginx.ingress.kubernetes.io/ssl-redirect: "true"
        nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
        nginx.ingress.kubernetes.io/auth-tls-verify-client: "on"
        nginx.ingress.kubernetes.io/auth-tls-secret: "flux-system/thanos-server-tls"
      # hosts:
      # - 'thanos.{{ printf "%.*s" 23 .params.CLUSTER_NAME }}.{{ .params.TEAM }}.{{ .params.AWS_ACCOUNT_NAME }}.w3ops.net'
      paths:
      - /
      pathType: ImplementationSpecific
      tls:
      - secretName: thanos-sidecar-tls
        # hosts:
        # - 'thanos.{{ printf "%.*s" 23 .params.CLUSTER_NAME }}.{{ .params.TEAM }}.{{ .params.AWS_ACCOUNT_NAME }}.w3ops.net'
prometheus-pushgateway:
  enabled: true
  serviceMonitor:
    enabled: true
    namespace: kube-system
