secrets:
  url: https://github.com/filecoin-project/gitops-profile-catalog
  path: "./profiles/secrets/prometheus"

region: us-west-2
clusterName: default

kube-prometheus-stack:
  fullnameOverride: weaveworks-prometheus
  enabled: true
  grafana:
    enabled: false
  prometheus:
    prometheusSpec:
      thanos: 
        objectStorageConfig: 
          key: thanos-storage-config.yaml
          name: thanos-storage-config
    serviceAccount:
      annotations:
        eks.amazonaws.com/role-arn: ""
    thanosIngress:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt"
        nginx.ingress.kubernetes.io/ssl-redirect: "true"
        nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
      hosts:
      - thanos-sidecar.example
      paths:
      - /
      pathType: ImplementationSpecific
      tls:
      - secretName: thanos-sidecar-tls
        hosts:
        - thanos-sidecar.example
