flux-application:
  namespaceOverride: flux-system
  secrets:
    url: "https://github.com/filecoin-project/gitops-profile-catalog"
    path: "./secrets/prometheus"
    branch: main

kube-prometheus-stack:
  fullnameOverride: weaveworks-prometheus
  enabled: true
  defaultRules:
    rules:
      kubeScheduler: false
      kubeApiserverAvailability: false
  grafana:
    enabled: false
  alertmanager:
    enabled: true
    alertmanagerSpec:
      replicas: 3
      secrets: ["alertmanager-slack-urls", "opsgenie-api-tokens"]
    templateFiles:
      slack.tmpl: >-
        {{`{{`}} define "slack.filecoin.text" {{`}}`}}
        {{`{{ range .Alerts -}}`}}
        *Alert:* {{`{{ .Annotations.title }}`}}{{`{{ if .Labels.severity }}`}} - `{{`{{ .Labels.severity }}`}}`{{`{{ end }}`}}

        *Description:* {{`{{ .Annotations.description }}`}}

        *Details:*
         {{`{{ range .Labels.SortedPairs }}`}} • *{{`{{ .Name }}`}}:* `{{`{{ .Value }}`}}`
         {{`{{ end }}`}}
        {{`{{ end }}`}}
        {{`{{ end }}`}}
    config:
      route:
        group_by: ["alertname", "cluster"]
        group_wait: 500ms
        receiver: "null"
        group_interval: 500ms
        repeat_interval: 1d
        routes:
          - match:
              severity: "critical"
            receiver: "slack-alerts"
          - match:
              severity: "page"
            receiver: "opsgenie"
      templates:
        - '/etc/alertmanager/config/*.tmpl'
      receivers:
        - name: "null"
        - name: "opsgenie"
          opsgenie_configs:
          - send_resolved: true
            api_key_file: "/etc/alertmanager/secrets/opsgenie-api-tokens/{{ .params.TEAM }}-alerts"
        - name: "slack-alerts"
          slack_configs:
          - channel: "#{{ .params.TEAM }}-alerts-confidential"
            api_url_file: "/etc/alertmanager/secrets/alertmanager-slack-urls/{{ .params.TEAM }}-alerts"
            title: "[{{`{{ .Alerts.Firing | len }}`}} Firing] {{`{{ .CommonLabels.severity }}`}} {{`{{ .GroupLabels.alertname }}`}}"
            text: |-
              {{`{{`}} template "slack.filecoin.text" . {{`}}`}}
            send_resolved: true
  prometheus:
    prometheusSpec:
      externalLabels:
        cluster: '{{ or (.params).CLUSTER_NAME "test-cluster" }}'
      replicaExternalLabelName: __replica__
      thanos:
        objectStorageConfig:
          key: objstore.yml
          name: thanos-storage-config
      retention: 2d
      retentionSize: "15GB"
      ruleSelectorNilUsesHelmValues: false
      serviceMonitorSelectorNilUsesHelmValues: false
      podMonitorSelectorNilUsesHelmValues: false
      storageSpec:
        volumeClaimTemplate:
          spec:
            storageClassName: gp2
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 20Gi
    serviceAccount:
      annotations:
        eks.amazonaws.com/role-arn: 'arn:aws:iam::{{ .params.AWS_ACCOUNT_ID }}:role/{{ .params.CLUSTER_NAME }}-monitoring'
    thanosIngress:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt"
        nginx.ingress.kubernetes.io/ssl-redirect: "true"
        nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
        nginx.ingress.kubernetes.io/auth-tls-verify-client: "on"
        nginx.ingress.kubernetes.io/auth-tls-secret: "flux-system/thanos-server-tls"
      hosts:
      - 'thanos.{{ printf "%.*s" 23 (.params).CLUSTER_NAME }}.{{ or (.params).TEAM "netops" }}.{{ or (.params).AWS_ACCOUNT_NAME "netops" }}.w3ops.net'
      paths:
      - /
      pathType: ImplementationSpecific
      tls:
      - secretName: thanos-sidecar-tls
        hosts:
        - 'thanos.{{ printf "%.*s" 23 (.params).CLUSTER_NAME }}.{{ or (.params).TEAM "netops" }}.{{ or (.params).AWS_ACCOUNT_NAME "netops" }}.w3ops.net'
prometheus-pushgateway:
  enabled: true
  serviceMonitor:
    enabled: true
    namespace: kube-system
thanos:
  enabled: true
  existingObjstoreSecret: thanos-storage-config
  compactor:
    enabled: true
    retentionResolution5m: 90d
    serviceAccount:
      annotations:
        eks.amazonaws.com/role-arn: 'arn:aws:iam::{{ or (.params).AWS_ACCOUNT_ID "55555555555" }}:role/{{ or (.params).CLUSTER_NAME "test-cluster" }}-thanos-compactor'
  query:
    enabled: false
  queryFrontend:
    enabled: false
  storegateway:
    enabled: false
thanos-bucket-config:
  region: '{{ or (.params).AWS_REGION "us-east-1" }}'
  clusterName: '{{ or (.params).CLUSTER_NAME "test-cluster" }}'
