secrets:
  url: https://github.com/filecoin-project/gitops-profile-catalog
  path: "./secrets/dex/wge-nonprod"

sourceRef:
  namespace: wego-system
  name: wego-auto-github-gitops-root
dex:
  enabled: true
  config:
    issuer: https://nonprod-auth.w3ops.net
    storage:
      type: memory
    enablePasswordDB: true

  serviceMonitor:
    # -- Enable Prometheus ServiceMonitor.
    # See the [documentation](https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/design.md#servicemonitor) and the [API reference](https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#servicemonitor) for details.
    enabled: false
  
    # -- Namespace where the ServiceMonitor resource should be deployed.
    # @default -- Release namespace.
    namespace: "monitoring"
  
    # -- (duration) Prometheus scrape interval.
    interval: 1h
  
    # -- (duration) Prometheus scrape timeout.
    scrapeTimeout: 15m
  
    # -- Labels to be added to the ServiceMonitor.
    labels: {"dex", "wge"}


  ingress:
    enabled: true
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
    hosts:
      - host: nonprod-auth.w3ops.net
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
    - hosts:
      - nonprod-auth.w3ops.net
      secretName: dex-cert
  envFrom:
  - secretRef:
      name: dex-auth
  - secretRef:
      name: oidc-auth
