secrets:
  url: https://github.com/filecoin-project/gitops-profile-catalog
  path: "./secrets/dex/wge-nonprod"

sourceRef:
  namespace: wego-system
  name: wego-auto-github-gitops-root
dex:
  enabled: true
  config:
    issuer: https://nonprod-auth.w3ops.net
    storage:
      type: memory
    enablePasswordDB: true
  ingress:
    enabled: true
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
    hosts:
      - host: nonprod-auth.w3ops.net
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
    - hosts:
      - nonprod-auth.w3ops.net
      secretName: dex-cert
  envFrom:
  - secretRef:
      name: dex-auth
  - secretRef:
      name: oidc-auth
