kustomization:
  path: "./profiles/dex/wge-nonprod/secrets"
sourceRef:
  namespace: wego-system
  name: wego-auto-github-gitops-root
dex:
  ingress:
    enabled: true
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
  envFrom:
  - secretRef:
      name: dex-auth
  - secretRef:
      name: oidc-auth