---
# Source: generic-template/templates/template.yaml
apiVersion: capi.weave.works/v1alpha1
kind: CAPITemplate
metadata:
  name: generic-template
  namespace:  default
  annotations:
    capi.weave.works/profile-0: '{"name": "k8s-rbac-permissions", "version": "0.0.8","values:" "adminGroups:\n- org: filecoin-project\n  team: bedrock-go\n- org: filecoin-project\n  team: Weaveworks\n- org: filecoin-project\n  team: infra"}'
    capi.weave.works/profile-1: '{"name": "external-dns", "version": "0.0.9"}'
    capi.weave.works/profile-2: '{"name": "cert-manager", "version": "2.0.1"}'
    capi.weave.works/profile-3: '{"name": "cert-manager-issuer", "version": "0.0.4"}'
    capi.weave.works/profile-4: '{"name": "ebs-csi-controller", "version": "0.0.2"}'
    capi.weave.works/profile-5: '{"name": "aws-node-term-handler", "version": "0.0.1"}'
    capi.weave.works/profile-6: '{"name": "aws-load-balancer-controller", "version": "0.0.2"}'
    capi.weave.works/profile-7: '{"name": "prometheus", "version": "1.1.8"}'
    capi.weave.works/profile-8: '{"name": "ingress-nginx", "version": "0.0.12"}'
    capi.weave.works/profile-9: '{"name": "policy-agent", "version": "0.2.11"}'
    capi.weave.works/profile-10: '{"name": "promtail", "version": "0.0.5"}'
  labels:
    helm.sh/chart: generic-template-0.0.1
    app.kubernetes.io/name: generic-template
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/managed-by: Helm     
spec:
  renderType: templating
  description: An AWS EKS template that creates a cluster
  params:
    - name: CLUSTER_NAME
      description: The name for this cluster.
    - name: MAX_NODES_NODEGROUP_0
      description: max nodes for 0
    - name: MIN_NODES_NODEGROUP_0
      description: min nodes for 0
      options:
      - t3.large
      - t3.xlarge
      - m5a.large
      - m5a.xlarge
      - m5a.2xlarge
      - c5a.xlarge
      - c5a.2xlarge
      - c5a.4xlarge
      - t3.2xlarge
      - r5.8xlarge
    - name: MAX_NODES_NODEGROUP_1
      description: max nodes for 1
    - name: MIN_NODES_NODEGROUP_1
      description: min nodes for 1
      options:
      - t3.large
      - t3.xlarge
      - m5a.large
      - m5a.xlarge
      - m5a.2xlarge
      - c5a.xlarge
      - c5a.2xlarge
      - c5a.4xlarge
      - t3.2xlarge
      - r5.8xlarge

    
  resourcetemplates:
  
  - apiVersion: gitops.weave.works/v1alpha1
    kind: GitopsCluster
    metadata:
      name: '{{ .params.CLUSTER_NAME }}'
      namespace: '{{ .params.NAMESPACE }}'
      labels:
        weave.works/capi: '{{ .params.CLUSTER_NAME }}-bootstrap-v3'
    spec:
      capiClusterRef:
        name: '{{ .params.CLUSTER_NAME }}'
  
  - apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: AWSMachineTemplate
    metadata:
      name: '{{ .params.CLUSTER_NAME }}-machine-deployment-0'
    spec:
      template:
        spec:
          instanceType: '{{ .params.INSTANCE_TYPE_NODEGROUP_0 }}'
          iamInstanceProfile: 'wge-{{ .params.GITOPS_ENV }}-{{ .params.AWS_ACCOUNT_NAME }}-node-instance-profile'
          sshKeyName: ""
  - apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
    kind: EKSConfigTemplate
    metadata:
      name: '{{ .params.CLUSTER_NAME }}-machine-deployment-0-0'
    spec:
      template: {}
  - apiVersion: cluster.x-k8s.io/v1beta1
    kind: MachineDeployment
    metadata:
      name: '{{ .params.CLUSTER_NAME }}-machine-deployment-0-0'
      namespace: '{{ .params.NAMESPACE }}'
      annotations:
        cluster.x-k8s.io/cluster-api-autoscaler-node-group-min-size: "{{ .params.MIN_NODES_NODEGROUP_0 }}"
        cluster.x-k8s.io/cluster-api-autoscaler-node-group-max-size: "{{ .params.MAX_NODES_NODEGROUP_0 }}"
        kustomize.toolkit.fluxcd.io/prune: disabled
      clusterName: '{{ .params.CLUSTER_NAME }}'
      selector:
        matchLabels:
      template:
        metadata:
          labels:
            min: nodes-{{ .params.MIN_NODES_NODEGROUP_0 }}
            max: nodes-{{ .params.MAX_NODES_NODEGROUP_0 }}
        spec:
          clusterName: '{{ .params.CLUSTER_NAME }}'
          version: '{{ .params.KUBERNETES_VERSION }}'
          failureDomain: '{{ .params.AWS_REGION }}a'
          bootstrap:
            configRef:
              name: '{{ .params.CLUSTER_NAME }}-machine-deployment-0-0'
              apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
              kind: EKSConfigTemplate
          infrastructureRef:
            name: '{{ .params.CLUSTER_NAME }}-machine-deployment-0-0'
            apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
            kind: AWSMachineTemplate
  - apiVersion: cluster.x-k8s.io/v1beta1
    kind: MachineDeployment
    metadata:
      name: '{{ .params.CLUSTER_NAME }}-machine-deployment-0-1'
      namespace: '{{ .params.NAMESPACE }}'
      annotations:
        cluster.x-k8s.io/cluster-api-autoscaler-node-group-min-size: "{{ .params.MIN_NODES_NODEGROUP_0 }}"
        cluster.x-k8s.io/cluster-api-autoscaler-node-group-max-size: "{{ .params.MAX_NODES_NODEGROUP_0 }}"
        kustomize.toolkit.fluxcd.io/prune: disabled
      clusterName: '{{ .params.CLUSTER_NAME }}'
      selector:
        matchLabels:
      template:
        metadata:
          labels:
            min: nodes-{{ .params.MIN_NODES_NODEGROUP_0 }}
            max: nodes-{{ .params.MAX_NODES_NODEGROUP_0 }}
        spec:
          clusterName: '{{ .params.CLUSTER_NAME }}'
          version: '{{ .params.KUBERNETES_VERSION }}'
          failureDomain: '{{ .params.AWS_REGION }}b'
          bootstrap:
            configRef:
              name: '{{ .params.CLUSTER_NAME }}-machine-deployment-0-0'
              apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
              kind: EKSConfigTemplate
          infrastructureRef:
            name: '{{ .params.CLUSTER_NAME }}-machine-deployment-0-0'
            apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
            kind: AWSMachineTemplate
  - apiVersion: cluster.x-k8s.io/v1beta1
    kind: MachineDeployment
    metadata:
      name: '{{ .params.CLUSTER_NAME }}-machine-deployment-0-2'
      namespace: '{{ .params.NAMESPACE }}'
      annotations:
        cluster.x-k8s.io/cluster-api-autoscaler-node-group-min-size: "{{ .params.MIN_NODES_NODEGROUP_0 }}"
        cluster.x-k8s.io/cluster-api-autoscaler-node-group-max-size: "{{ .params.MAX_NODES_NODEGROUP_0 }}"
        kustomize.toolkit.fluxcd.io/prune: disabled
      clusterName: '{{ .params.CLUSTER_NAME }}'
      selector:
        matchLabels:
      template:
        metadata:
          labels:
            min: nodes-{{ .params.MIN_NODES_NODEGROUP_0 }}
            max: nodes-{{ .params.MAX_NODES_NODEGROUP_0 }}
        spec:
          clusterName: '{{ .params.CLUSTER_NAME }}'
          version: '{{ .params.KUBERNETES_VERSION }}'
          failureDomain: '{{ .params.AWS_REGION }}c'
          bootstrap:
            configRef:
              name: '{{ .params.CLUSTER_NAME }}-machine-deployment-0-0'
              apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
              kind: EKSConfigTemplate
          infrastructureRef:
            name: '{{ .params.CLUSTER_NAME }}-machine-deployment-0-0'
            apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
            kind: AWSMachineTemplate
  - apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: AWSMachineTemplate
    metadata:
      name: '{{ .params.CLUSTER_NAME }}-machine-deployment-1'
    spec:
      template:
        spec:
          instanceType: '{{ .params.INSTANCE_TYPE_NODEGROUP_1 }}'
          iamInstanceProfile: 'wge-{{ .params.GITOPS_ENV }}-{{ .params.AWS_ACCOUNT_NAME }}-node-instance-profile'
          sshKeyName: ""
  - apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
    kind: EKSConfigTemplate
    metadata:
      name: '{{ .params.CLUSTER_NAME }}-machine-deployment-1-0'
    spec:
      template: {}
  - apiVersion: cluster.x-k8s.io/v1beta1
    kind: MachineDeployment
    metadata:
      name: '{{ .params.CLUSTER_NAME }}-machine-deployment-1-0'
      namespace: '{{ .params.NAMESPACE }}'
      annotations:
        cluster.x-k8s.io/cluster-api-autoscaler-node-group-min-size: "{{ .params.MIN_NODES_NODEGROUP_1 }}"
        cluster.x-k8s.io/cluster-api-autoscaler-node-group-max-size: "{{ .params.MAX_NODES_NODEGROUP_1 }}"
        kustomize.toolkit.fluxcd.io/prune: disabled
      clusterName: '{{ .params.CLUSTER_NAME }}'
      selector:
        matchLabels:
      template:
        metadata:
          labels:
            min: nodes-{{ .params.MIN_NODES_NODEGROUP_1 }}
            max: nodes-{{ .params.MAX_NODES_NODEGROUP_1 }}
        spec:
          clusterName: '{{ .params.CLUSTER_NAME }}'
          version: '{{ .params.KUBERNETES_VERSION }}'
          failureDomain: '{{ .params.AWS_REGION }}a'
          bootstrap:
            configRef:
              name: '{{ .params.CLUSTER_NAME }}-machine-deployment-1-0'
              apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
              kind: EKSConfigTemplate
          infrastructureRef:
            name: '{{ .params.CLUSTER_NAME }}-machine-deployment-1-0'
            apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
            kind: AWSMachineTemplate
  - apiVersion: cluster.x-k8s.io/v1beta1
    kind: MachineDeployment
    metadata:
      name: '{{ .params.CLUSTER_NAME }}-machine-deployment-1-1'
      namespace: '{{ .params.NAMESPACE }}'
      annotations:
        cluster.x-k8s.io/cluster-api-autoscaler-node-group-min-size: "{{ .params.MIN_NODES_NODEGROUP_1 }}"
        cluster.x-k8s.io/cluster-api-autoscaler-node-group-max-size: "{{ .params.MAX_NODES_NODEGROUP_1 }}"
        kustomize.toolkit.fluxcd.io/prune: disabled
      clusterName: '{{ .params.CLUSTER_NAME }}'
      selector:
        matchLabels:
      template:
        metadata:
          labels:
            min: nodes-{{ .params.MIN_NODES_NODEGROUP_1 }}
            max: nodes-{{ .params.MAX_NODES_NODEGROUP_1 }}
        spec:
          clusterName: '{{ .params.CLUSTER_NAME }}'
          version: '{{ .params.KUBERNETES_VERSION }}'
          failureDomain: '{{ .params.AWS_REGION }}b'
          bootstrap:
            configRef:
              name: '{{ .params.CLUSTER_NAME }}-machine-deployment-1-0'
              apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
              kind: EKSConfigTemplate
          infrastructureRef:
            name: '{{ .params.CLUSTER_NAME }}-machine-deployment-1-0'
            apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
            kind: AWSMachineTemplate
  - apiVersion: cluster.x-k8s.io/v1beta1
    kind: MachineDeployment
    metadata:
      name: '{{ .params.CLUSTER_NAME }}-machine-deployment-1-2'
      namespace: '{{ .params.NAMESPACE }}'
      annotations:
        cluster.x-k8s.io/cluster-api-autoscaler-node-group-min-size: "{{ .params.MIN_NODES_NODEGROUP_1 }}"
        cluster.x-k8s.io/cluster-api-autoscaler-node-group-max-size: "{{ .params.MAX_NODES_NODEGROUP_1 }}"
        kustomize.toolkit.fluxcd.io/prune: disabled
      clusterName: '{{ .params.CLUSTER_NAME }}'
      selector:
        matchLabels:
      template:
        metadata:
          labels:
            min: nodes-{{ .params.MIN_NODES_NODEGROUP_1 }}
            max: nodes-{{ .params.MAX_NODES_NODEGROUP_1 }}
        spec:
          clusterName: '{{ .params.CLUSTER_NAME }}'
          version: '{{ .params.KUBERNETES_VERSION }}'
          failureDomain: '{{ .params.AWS_REGION }}c'
          bootstrap:
            configRef:
              name: '{{ .params.CLUSTER_NAME }}-machine-deployment-1-0'
              apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
              kind: EKSConfigTemplate
          infrastructureRef:
            name: '{{ .params.CLUSTER_NAME }}-machine-deployment-1-0'
            apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
            kind: AWSMachineTemplate
