external-dns:
  rbac:
    create: true
  txtOwnerId: '{{ or (.params).CLUSTER_NAME "test-cluster" }}'
  domainFilters:
  - w3ops.net
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::{{ or (.params).AWS_ACCOUNT_ID "55555555555" }}:role/{{ or (.params).CLUSTER_NAME "test-cluster" }}-external-dns
