apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: prometheus-secrets
  namespace: {{ template "prometheus.namespace" . }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
  labels:
    app: {{ template "prometheus.name" . }}
    chart: {{ template "prometheus.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  interval: 5m
  decryption:
    provider: sops
    secretRef:
      name: profiles-sops-gpg
  path: "./profiles/prometheus/secrets"
  prune: true
  sourceRef:
    kind: GitRepository
    name: wego-auto-github-gitops-root
  timeout: 2m