apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations: {}
  labels: {}
  name: ipfs-operator-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ipfs-operator-manager-role
subjects:
- kind: ServiceAccount
  name: ipfs-operator-controller-manager
  namespace: ipfs-operator-system
