apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations: {}
  labels: {}
  name: ipfs-operator-leader-election-rolebinding
  namespace: ipfs-operator-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ipfs-operator-leader-election-role
subjects:
- kind: ServiceAccount
  name: ipfs-operator-controller-manager
  namespace: ipfs-operator-system
