# The secrets are designed to perform the following functions:
# - Provide a github token to pull a private repo
# - Pass profiles secrets to leaf clusters
secrets:
  url: "https://github.com/filecoin-project/gitops-profile-catalog"
  path: "./secrets/flux-application"
  branch: main
  key: wge-profiles-sops-gpg
  serviceAccountName: kustomize-controller
  targetNamespace: flux-system
  
# Used to configure a GitRepo and a Kustomization for applications
app:
  create: false
#   url: "https://github.com/filecoin-project/lotus-infra"
#   path: "./kubernetes/gitops/prod/us-east-2/cluster"
#   branch: gitops-poc
#   # key: ""
#   token: flux-application-github-token
