apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8s-oidc-admin
  labels:
    {{- include "k8s-rbac-permissions.labels" . | nindent 4 }}   
rules:
- apiGroups:
  - ""
  resources: ["*"]
  verbs:
  - get
  - list
  - watch