region: us-west-2
clusterName: default
thanos:
  objectStorageConfig:
    key: thanos-storage-config.yaml
    name: thanos-storage-config
  compactor:
    retentionResolution5m: 90d
  query:
    enabled: false
  queryFrontend:
    enabled: false
  storegateway:
    enabled: false
