secrets:
  url: https://github.com/filecoin-project/gitops-profile-catalog
  path: "./profiles/secrets/thanos"

thanos:
  existingObjstoreSecret: thanos-storage-config
  compactor:
    enabled: true
    retentionResolution5m: 90d
    serviceAccount:
      annotations:
        eks.amazonaws.com/role-arn: ""
  query:
    enabled: false
  queryFrontend:
    enabled: false
  storegateway:
    enabled: false
