apiVersion: v1
stringData:
    LOGZIO_LOGS_SHIPPING_TOKEN: ENC[AES256_GCM,data:GP3IGDW52JAD2TU8L86jAxcKLHeeN0xQMJ6nEuNvpbU=,iv:aPNo9x1/vL+YDUycKU8p73HUSGE5DroCi82rQQVUaEY=,tag:PsfF5WNs/DxoURpikMQ56w==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: logzio-log-shipping-auth
    namespace: flux-system
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-07-22T13:35:11Z"
    mac: ENC[AES256_GCM,data:rdQnZiyE/dPxMeZdmk7fxFYXYurXNxuEnVXaxaJkdnbb44z5U3SqTEzb2lq4Bd3lgpChuyp50Ly3NRb69hKPE2eR8j/lS2NlkYlzvDBe6M1HUa/lXRpnCQIsIgrOXQk0XJ9YfKM7lFO/YJgjIMSDu655XhcJ0OK5L+RNQn5oeKA=,iv:RWcn4G/pfBGfE7gDscjAklLHJj1y30k1eBo9yPrUlME=,tag:vhIM7sMmWPb5cjIN3belYQ==,type:str]
    pgp:
        - created_at: "2022-07-22T13:35:10Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA2IWPpjKSDN/AQ//et+zLViTcLm9NIj+IGET/5qF63xuOrWdZkHumV5cWS0V
            kGvhKbSMNEOwc5FHOnwCVTz+GzxEySk+Ui1pAMOdryrlIEpevIGm3Rlwzv/ftRfX
            oTypuhsD5MbSEQsGpVGSY0FvxiiqNHqLv3V5OQdPMvtkI+IU9pRTV5CyvoZ1hifC
            T/aEAHt4JtQj5iHK2yWqtzfLvaSSk7lm5WJ6Ct04PBJ1QUnvI+rClCIlquo7e32T
            wZQ5lv3po/m/eTc9cFIqxuKNHO1BQdc8FqGCPGXMCoJR5I6wypLgZcBkG1j9SrEL
            UEOKHo/1/6fZcDGm0z7EdNmwBxTwxnJG19LCKTjR6uSvyX4Y5HcgXUukcpVkVZJY
            MMXaILV00AyfVI9wM3SNpDgkTybwvO4ZPim4t4/BlwbjIEzA5YnEVqpLa5fKWNsY
            ed8MhVyTg+rV9PEvfVaR/7iCEylleeymXLhshAlbM8tjdejysaVGaYN30NtIk/aY
            gkJzKchDFxyogIkjWwR9Uw7/na2oQAWygmAP3+s4YwFqdC/gxihmffwXliTEw72a
            ehXRtQi8iOKRfAezmQhs7TDYp4hM0ZOZY0qywj6AzUCG1N3AXoIpunkHBdK3df5R
            gFW3FuYacavdVGa0UjU5n8igjKyO6xH9FsQuKavhVW/j/6ZSa9uClEf+QLWvk7vU
            aAEJAhBkbaO0Q6Mx9XZiGryOLeony0EF1ks6G0TswlLgesAJomjFdo+Q9MHhHAfx
            O0F1HsuMu9F/vv+pkFkhF4bmENgbT6oQ1yeCyP3200Xxbl63cCDhLCP2Y4SATze1
            d6KKlXMrTJqO
            =PPQg
            -----END PGP MESSAGE-----
          fp: 3C778F802D79787BCE9D795CE20F63D488FC275F
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
