apiVersion: v2
description: A Weaveworks Helm chart for Kubernetes to configure the policy agent
name: policy-agent
appVersion: "1.0"
version: 1.0.0
kubeVersion: ">=1.16.0-0"
icon: https://www.magalix.com/hubfs/Imported%20images/logo-02.png%3Fwidth=560%26name=logo-02-Dec-18-2020-11-24-41-75-AM.png
type: application
home: https://github.com/weaveworks/profiles-catalog
sources:
  - https://github.com/weaveworks/policy-agent

keywords:
- policy

maintainers:
  - name: Weaveworks
    email: support@weave.works

annotations:
  "weave.works/profile": policy-agent
  "weave.works/layer": layer-1
  "weave.works/category": Policy
  "weave.works/operator": "true"
  "weave.works/links": |
    - name: Upstream Project
      url: https://github.com/weaveworks/policy-agent
  "weave.works/profile-ci": |
    - "gke"
    - "kind"

dependencies:
- name: weave-policy-agent
  version: "0.5.0"
  repository: "https://weaveworks.github.io/profiles-catalog/"
- name: flux-application
  version: "0.1.1"
  repository: "file://../flux-application"