weave-policy-agent:
  policy-agent:
    image: magalixcorp/policy-agent
    failurePolicy: Ignore

    # If you don't want to use cert-manager, set useCertManager to false and provide your own certs
    useCertManager: true
    certificate: ""
    key: ""
    caCertificate: ""

    persistence:
      enabled: false
      # claimStorage: 1Gi
      # sinkDir: /tmp
      # storageClassName: standard
    config:
      accountId: "policy-acct-v1"
      clusterId: "policy-cltr-v1"
      audit:
        # Enable audit functionality
        enabled: true
        sinks:
          # Enable writing violations as K8s events
          k8sEventsSink:
            enabled: true
      admission:
        # Enable admission functionality
        enabled: false
        sinks:
          # Enable writing violations as K8s events
          k8sEventsSink:
            enabled: true
  policySource:
    enabled: true
    url: ssh://git@github.com/filecoin-project/gitops-policy-library
    branch: wge-profile-dev
    path: ./                                             # Could be a path to the policies dir or a kustomization.yaml file
    secretRef: policy-library-auth                       # (Optional): Name of the K8s secret with private repo auth credentials

flux-application:
  namespaceOverride: flux-system
  secrets:
    url: "https://github.com/filecoin-project/gitops-profile-catalog"
    path: "./secrets/policy-agent"
    branch: main
    serviceAccountName: kustomize-controller
