image: magalixcorp/policy-agent:latest
namespace: policy-system
failurePolicy: Ignore

# If you don't want to use cert-manager, set useCertManager to false and provide your own certs
useCertManager: true
certificate: ""
key: ""
caCertificate: ""

persistence:
  enabled: false
  # claimStorage: 1Gi
  # sinkDir: /tmp
  # storageClassName: standard

config:
  # The path on the K8s node in which the agent writes the violation. 
  # This can be used for reporting, observability, etc...
  AGENT_FILESYSTEM_SINK_FILE_PATH: "/tmp/result.json"

  # Enable writing violations as K8s events
  AGENT_ENABLE_K8S_EVENTS_SINK: "true"

  # Enable pushing violations to flux notification controller
  # AGENT_FLUX_NOTIFICATION_SINK_ADDR: <flux-notification-controller-svc>

  # Enable admission functionality, "1" true or "0" false
  AGENT_ENABLE_ADMISSION: "1"

  # Enable audit functionality, "1" true or "0" false
  AGENT_ENABLE_AUDIT: "1" 

policySource:
  enabled: true
  url: ssh://git@github.com/cmharden/policy-library
  branch: wge-profile-dev
  path: ./                                             # Could be a path to the policies dir or a kustomization.yaml file
  secretRef: policy-library-auth                       # (Optional): Name of the K8s secret with private repo auth credentials

accountId: "policy-acct-v1"
clusterId: "policy-cltr-v1"

secrets:
  url: https://github.com/filecoin-project/gitops-profile-catalog
  path: "./secrets/policy-agent"
  serviceAccountName: kustomize-controller
