{{- range $nodeGroup := .Values.nodeGroups }}
- apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
  kind: AWSMachineTemplate
  metadata:
    name: '{{`{{ .params.CLUSTER_NAME }}`}}-machine-deployment-0-0'
  spec:
    template:
      spec:
        instanceType: '{{`{{ .params.INSTANCE_TYPE_NODEGROUP_0 }}`}}'
        iamInstanceProfile: 'wge-{{`{{ .params.GITOPS_ENV }}`}}-{{`{{ .params.AWS_ACCOUNT_NAME }}`}}-node-instance-profile'
        sshKeyName: ""
- apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
  kind: EKSConfigTemplate
  metadata:
    name: '{{ .params.CLUSTER_NAME }}-machine-deployment-0-0'
  spec:
    template: {}
- apiVersion: cluster.x-k8s.io/v1beta1
  kind: MachineDeployment
  metadata:
    name: '{{ .params.CLUSTER_NAME }}-machine-deployment-0-0'
    namespace: '{{ .params.NAMESPACE }}'
    annotations:
      cluster.x-k8s.io/cluster-api-autoscaler-node-group-min-size: "{{ .params.MIN_NODES_NODEGROUP_0 }}"
      cluster.x-k8s.io/cluster-api-autoscaler-node-group-max-size: "{{ .params.MAX_NODES_NODEGROUP_0 }}"
      kustomize.toolkit.fluxcd.io/prune: disabled
  spec:
    clusterName: '{{ .params.CLUSTER_NAME }}'
    selector:
      matchLabels:
    template:
      metadata:
        labels:
          min: nodes-{{ .params.MIN_NODES_NODEGROUP_0 }}
          max: nodes-{{ .params.MAX_NODES_NODEGROUP_0 }}
      spec:
        clusterName: '{{ .params.CLUSTER_NAME }}'
        version: '{{ .params.KUBERNETES_VERSION }}'
        failureDomain: '{{ .params.AWS_REGION }}a'
        bootstrap:
          configRef:
            name: '{{ .params.CLUSTER_NAME }}-machine-deployment-0-0'
            apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
            kind: EKSConfigTemplate
        infrastructureRef:
          name: '{{ .params.CLUSTER_NAME }}-machine-deployment-0-0'
          apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
          kind: AWSMachineTemplate
  {{- end }}