apiVersion: capi.weave.works/v1alpha1
kind: CAPITemplate
metadata:
  name: {{ .Values.name }}
  namespace:  {{ template "generic-template.namespace" . }}
  annotations:
  {{- range $key,$profile := .Values.requiredProfiles }}
    capi.weave.works/profile-{{ $key }}: '{"name": "{{ $profile.name }}", "version": "{{ $profile.version }}"{{if ($profile.values) }},"values:" "{{ $profile.values}} "{{ end }}}'
  {{- end }}
  labels:
    {{- include "generic-template.labels" . | nindent 4 }}     
spec:
  renderType: templating
  description: {{ .Values.description }}
  params:
    - name: CLUSTER_NAME
      description: The name for this cluster.
    - name: AWS_REGION
      description: Region for cluster
      options:
      {{- range $val := .Values.maxOptions }}
      - {{ $val }}
      {{- end }}
    {{- range $nodeGroup := .Values.nodeGroups }}
    - name: MAX_NODES_NODEGROUP_{{ $nodeGroup.name }}
      description: max nodes for {{ $nodeGroup.name }}
      options:
      {{- range $val := $nodeGroup.maxnOptions }}
      - {{ $val }}
      {{- end }}
    - name: MIN_NODES_NODEGROUP_{{ $nodeGroup.name }}
      description: min nodes for {{ $nodeGroup.name }}
      options:
      {{- range $val := $nodeGroup.minOptions }}
      - {{ $val }}
      {{- end }}
    {{- end }}
  resourcetemplates:
{{- $currentScope := . -}}
{{- range $path, $_ :=  .Files.Glob  "**.yaml" -}}
    {{- with $currentScope -}}
        {{- tpl ( .Files.Get $path ) . | nindent 2 -}}
    {{- end -}}
{{- end -}}
