apiVersion: v2
name: release-metrics-exporters
description: A suite of Prometheus Exporters to caputre release metrics from github, docker hub, homebrew, and snapcraft.
type: application
version: "0.0.6"
appVersion: "0.0.0"

annotations:
  "weave.works/profile": release-metrics-exporters
  "weave.works/category": Observability
  "weave.works/layer": layer-2
  "weave.works/links": |
    - name: Release Metrics Application Repo
      url: https://github.com/filecoin-project/release-metrics-gitops
    - name: Snapcraft Exporter
      url: https://github.com/filecoin-project/snapcraft-exporter
    - name: Homebrew Exporter
      url: https://github.com/filecoin-project/homebrew-exporter
    - name: Github Exporter
      url: https://github.com/filecoin-project/github-exporter
    - name: DockerHub Exporter
      url: https://github.com/filecoin-project/docker-hub-exporter

sources:
  - https://github.com/filecoin-project/snapcraft-exporter
  - https://github.com/filecoin-project/homebrew-exporter
  - https://github.com/filecoin-project/github-exporter
  - https://github.com/filecoin-project/docker-hub-exporter

keywords:
  - release-metrics
  - homebrew
  - snapcraft
  - github
  - docker-hub

maintainers:
  - name: ianconsolata
    email: ian.s.davis@protocol.ai

dependencies: []
