flux-application:
  secrets:
    url: "https://github.com/filecoin-project/gitops-profile-catalog"
    path: "./secrets/logzio-log-shipping-auth"
    branch: main

logzio-k8s-logs:
  extraEnvFrom:
  - secretRef:
      name: logzio-log-shipping-auth
  enabled: true
  secrets:
    create: true
    logzioRegion: "us"
    clusterName: ${CLUSTER_NAME}
    name: logzio-logs-secret
