apiVersion: capi.weave.works/v1alpha1
kind: CAPITemplate
metadata:
  name: {{ .Values.name }}
  namespace:  {{ template "template-base.namespace" . }}
  annotations:
  {{- range $key,$profile := .Values.requiredProfiles }}
    capi.weave.works/profile-{{ $key }}: '{"name": "{{ $profile.name }}", "version": "{{ $profile.version }}"{{if ($profile.values) }},"values": "{{ $profile.values}} "{{ end }}}'
  {{- end }}
  labels:
    {{- include "template-base.labels" . | nindent 4 }}     
spec:
  renderType: templating
  description: {{ .Values.description }}
  params:
    - name: CLUSTER_NAME
      description: The name for this cluster.
      required: true
    - name: AWS_ACCOUNT_NAME
      description: The name of the account for the cluster
      required: true
      options:
      {{- range $val := .Values.awsAccountOptions }}
      - {{ $val.name }}
      {{- end }}
    - name: NAMESPACE
      description: The namespace for this cluster
      required: true
      options:
      {{- range $val := .Values.namespaceOptions }}
      - {{ $val }}
      {{- end }}
    - name: TEAM
      description: Team/or Project
      required: true
      options:
      {{- range $val := .Values.teamOptions }}
      - {{ $val }}
      {{- end }}
    - name: AWS_REGION
      description: Region for cluster
      required: true
      options:
      {{- range $val := .Values.regionOptions }}
      - {{ $val }}
      {{- end }}
    {{- range $nodeGroup := .Values.nodeGroups }}
    - name: MAX_NODES_NODEGROUP_{{ $nodeGroup.name }}
      description: max nodes for {{ $nodeGroup.name }}
      required: true
      options:
      {{- range $val := $nodeGroup.maxOptions }}
      - {{ $val | quote }}
      {{- end }}
    - name: MIN_NODES_NODEGROUP_{{ $nodeGroup.name }}
      description: min nodes for {{ $nodeGroup.name }}
      required: true
      options:
      {{- range $val := $nodeGroup.minOptions }}
      - {{ $val | quote }}
      {{- end }}
    - name: INSTANCE_TYPE_NODEGROUP_{{ $nodeGroup.name }}
      description: intance type for {{ $nodeGroup.name }}
      required: true
      options:
      {{- range $val := $nodeGroup.instanceTypeOptions }}
      - {{ $val }}
      {{- end }}
    {{- end }}
  resourcetemplates:
{{- $currentScope := . -}}
{{- range $path, $_ :=  .Files.Glob  "**.yaml" -}}
    {{- with $currentScope -}}
        {{- tpl ( .Files.Get $path ) . | nindent 2 -}}
    {{- end -}}
{{- end -}}
