- apiVersion: v1
  data:
    kustomization.yaml: |
      apiVersion: kustomize.config.k8s.io/v1beta1
      kind: Kustomization
      resources:
      - flux.yaml
      patches:
        - patch: |
            - op: add
              path: /spec/template/spec/containers/0/args/0
              value: --no-cross-namespace-refs={{ .Values.flux.noCrossNamespaceRefs.enabled }}
          target:
            kind: Deployment
            name: "(kustomize-controller|helm-controller|notification-controller|image-reflector-controller|image-automation-controller)"
        - patch: |
            - op: add
              path: /spec/template/spec/containers/0/args/0
              value: --default-service-account=kustomize-controller
          target:
            kind: Deployment
            name: "(kustomize-controller|helm-controller)"
        - patch: |
            - op: add
              path: /spec/serviceAccountName
              value: kustomize-controller
          target:
            kind: Kustomization
            name: "flux-system"
        - patch: |
            apiVersion: v1
            kind: ServiceAccount
            metadata:
              name: kustomize-controller
              annotations:
                eks.amazonaws.com/role-arn: arn:aws:iam::{{ template "template-base.accountID" . }}:role/{{`{{ .params.CLUSTER_NAME }}`}}-kustomize-controller
          target:
            kind: ServiceAccount
            name: kustomize-controller
  kind: ConfigMap
  metadata:
    creationTimestamp: null
    name: '{{`{{ .params.CLUSTER_NAME }}`}}-flux-manifests'
