- apiVersion: iam.aws.crossplane.io/v1beta1
  kind: Policy
  metadata:
    name: '{{`{{ .params.CLUSTER_NAME }}`}}-kustomize-controller'
  spec:
    providerConfigRef:
      name: '{{`{{ .params.AWS_ACCOUNT_NAME }}`}}-provider'
    deletionPolicy: Delete
    forProvider:
      tags:
      - key: managedBy
        value: Weave GitOps Enterprise 
      - key: createdBy
        value: Crossplane 
      - key: cluster
        value: '{{`{{ .params.CLUSTER_NAME }}`}}'
      description: "For flux kustomize-controller"
      name: '{{`{{ .params.CLUSTER_NAME }}`}}-kustomize-controller'
      document: |
        {
            "Statement": [
                {
                    "Action": [
                        "kms:DescribeKey",
                        "kms:Decrypt"
                    ],
                    "Effect": "Allow",
                    "Resource": [
                        "*"
                    ],
                    "Sid": ""
                }
            ],
            "Version": "2012-10-17"
        }
- apiVersion: iam.aws.crossplane.io/v1beta1
  kind: Role
  metadata:
    name: '{{`{{ .params.CLUSTER_NAME }}`}}-kustomize-controller'
  spec:
    providerConfigRef:
      name: '{{`{{ .params.AWS_ACCOUNT_NAME }}`}}-provider'
    forProvider:
      tags:
      - key: managedBy
        value: Weave GitOps Enterprise 
      - key: createdBy
        value: Crossplane 
      - key: cluster
        value: '{{`{{ .params.CLUSTER_NAME }}`}}'
      assumeRolePolicyDocument: |
        {
            "Version": "2012-10-17",
            "Statement": [
                {
                    "Sid": "",
                    "Effect": "Allow",
                    "Principal": {
                        "Federated": "arn:aws:iam::{{ template "template-base.accountID" . }}:oidc-provider/oidc.eks.us-east-2.amazonaws.com/id/${EKS_CLUSTER_ID}"
                    },
                    "Action": "sts:AssumeRoleWithWebIdentity",
                    "Condition": {
                        "StringEquals": {
                            "oidc.eks.us-east-2.amazonaws.com/id/${EKS_CLUSTER_ID}:sub": [
                                "system:serviceaccount:flux-system:kustomize-controller"
                            ]
                        }
                    }
                }
            ]
        }
- apiVersion: iam.aws.crossplane.io/v1beta1
  kind: RolePolicyAttachment
  metadata:
    name: '{{`{{ .params.CLUSTER_NAME }}`}}-kustomize-controller'
  spec:
    providerConfigRef:
      name: '{{ .params.AWS_ACCOUNT_NAME }}-provider'
    forProvider:
      policyArnRef:
        name: '{{`{{ .params.CLUSTER_NAME }}`}}-kustomize-controller'
      roleNameRef:
        name: '{{`{{ .params.CLUSTER_NAME }}`}}-kustomize-controller'