{{- $environment := .Values.environment -}}
{{- range $nodeGroup := .Values.nodeGroups }}
- apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
  kind: AWSMachineTemplate
  metadata:
    name: '{{`{{ .params.CLUSTER_NAME }}`}}-{{`{{ .params.INSTANCE_TYPE_NODEGROUP_`}}{{ $nodeGroup.name }} }}-machine-deployment-{{ $nodeGroup.name }}-0'
    namespace: '{{`{{ .params.NAMESPACE }}`}}'
    annotations:
      kustomize.toolkit.fluxcd.io/prune: disabled
  spec:
    template:
      spec:
        instanceType: '{{`{{ .params.INSTANCE_TYPE_NODEGROUP_`}}{{ $nodeGroup.name }} }}'
        iamInstanceProfile: 'wge-{{ $environment }}-{{`{{ .params.AWS_ACCOUNT_NAME }}`}}-node-instance-profile'
        sshKeyName: ""
- apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
  kind: EKSConfigTemplate
  metadata:
    name: '{{`{{ .params.CLUSTER_NAME }}`}}-machine-deployment-{{ $nodeGroup.name }}-0'
    namespace: '{{`{{ .params.NAMESPACE }}`}}'
    annotations:
      kustomize.toolkit.fluxcd.io/prune: disabled
  spec:
    template: {}
{{- range $key,$az := $nodeGroup.availabilityZones }}
- apiVersion: cluster.x-k8s.io/v1beta1
  kind: MachineDeployment
  metadata:
    name: '{{`{{ .params.CLUSTER_NAME }}`}}-machine-deployment-{{ $nodeGroup.name }}-{{ $key }}'
    namespace: '{{`{{ .params.NAMESPACE }}`}}'
    annotations:
      cluster.x-k8s.io/cluster-api-autoscaler-node-group-min-size: "{{`{{ .params.MIN_NODES_NODEGROUP_`}}{{ $nodeGroup.name }} }}"
      cluster.x-k8s.io/cluster-api-autoscaler-node-group-max-size: "{{`{{ .params.MAX_NODES_NODEGROUP_`}}{{ $nodeGroup.name }} }}"
      kustomize.toolkit.fluxcd.io/prune: disabled
    clusterName: '{{`{{ .params.CLUSTER_NAME }}`}}'
  spec:
    clusterName: '{{`{{ .params.CLUSTER_NAME }}`}}'
    strategy: 
      type: RollingUpdate
      rollingUpdate:
        maxUnavailable: 1 
    selector:
      matchLabels:
    template:
      metadata:
        labels:
          min: nodes-{{`{{ .params.MIN_NODES_NODEGROUP_`}}{{ $nodeGroup.name }} }}
          max: nodes-{{`{{ .params.MAX_NODES_NODEGROUP_`}}{{ $nodeGroup.name }} }}
      spec:
        clusterName: '{{`{{ .params.CLUSTER_NAME }}`}}'
        version: '{{`{{ .params.KUBERNETES_VERSION }}`}}'
        failureDomain: '{{`{{ .params.AWS_REGION }}`}}{{ $az }}'
        bootstrap:
          configRef:
            name: '{{`{{ .params.CLUSTER_NAME }}`}}-machine-deployment-{{ $nodeGroup.name }}-0'
            apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
            kind: EKSConfigTemplate
        infrastructureRef:
          name: '{{`{{ .params.CLUSTER_NAME }}`}}-{{`{{ .params.INSTANCE_TYPE_NODEGROUP_`}}{{ $nodeGroup.name }} }}-machine-deployment-{{ $nodeGroup.name }}-0'
          apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
          kind: AWSMachineTemplate
{{- end }}
{{- end }}
