apiVersion: v2
name: template-filecoin-infra
description: A Weaveworks Helm chart for template-filecoin-infra
type: application
version: 0.0.31
kubeVersion: ">=1.16.0-0"
home: https://github.com/weaveworks/profiles-catalog
sources:
  - https://github.com/filecoin-project/gitops-profile-catalog

keywords:
- template-filecoin-infra

maintainers:
  - name: Weaveworks
    email: support@weave.works

dependencies:
- name: template-base
  version: "0.5.22"
  repository: "file://../template-base"
