apiVersion: v1
kind: Secret
metadata:
    name: github-auth
    namespace: storetheindex
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:OFokGl/6Dg==,iv:I/LawcQpIcLo3jD/ZzIpkgP4hrT1d4VRlMqo69J3Nwc=,tag:csSWfUz9JeOtpSKgwPzzAg==,type:str]
    password: ENC[AES256_GCM,data:zo9xoTNLukkYbm17jE5sHj/1siFBTAFk9vUpDTb6KGHboaJKW7LQWA==,iv:qKIubrHxSs4b2jpYuvF7mb8MLC/qioP4gP7Fa06g7u0=,tag:Ex42pQsySDwCrj/F+vws6A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-05-04T11:23:14Z"
    mac: ENC[AES256_GCM,data:/RErV51X4qHi7U+Narzk1i+lLosX0r28f3SZmt5pcSM95stqj6mPsywHwejs85g35j6nyUfrPi0TdLIT/AUHrTgsBFcvdhtj+uk/enq6/7F05rLjTRFCSj1PIDQDQYTSTsE6IW+QloXktIS4/F1xXR4kRe7yHnRwvYwREcIVJU4=,iv:5Yg/Tw8L6cKRaawv2T4PL23TjqJ3aySmZBDUNUkKxVc=,tag:rl2Jqlm8zKAExvSnm2Lj4A==,type:str]
    pgp:
        - created_at: "2022-05-04T11:23:13Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA2IWPpjKSDN/AQ//SiXGgIeQHQzRobqX2eYZpKjhDj4MWvaIqNo0pnI+d/8k
            ugpSHmZByB77W3IslkxiEOSJXqxyHgGG9mXBXpj+BBnYNrRA83ehAVd/qGlciezL
            0aXMFSv7Et5MEktR9KrLF1KgVJauUtkHeHO0DeFXzp9+QlIWKSkeIhY/7vEDGvOw
            /rKo+7HoRb7/VUgQMTLya3h7ogS0SeQPJx9ItIiqwVECnnQfB+o9JpAIBpxLLXqz
            siCkZBpIY2b3kGolGg0cNSU3HVY4uwFXlhOhv1FzPKGq3qlV34FV1cSU2rClH7K0
            Wm0UGpUUig4U14f3SZNV8p6EpRWiER3b21OODwP3ANCzDqfihg+nUbMqNfv87eUB
            zIo2gnU+bw0w9dJ/moIKoCKSV7tks6vRi9V/g8wAZjMLhG/+0WcBYrHyOLMm+ZLv
            PYV6T1iqLi/vZo1llQUxOD3rxzrMjT/F1LNRBEnmE62D3wzQdFEHgkpRAoaJJq0o
            ep50TO6W9pvNl0Fj/7yHn5CruHReS86eMRUs98Gn0QmyKEVoXzygEjqgIa+w/xN7
            Wq+gnG/IavxaRr/UVif/t7TrVZqKKkZ6qHuqJn5JluSz/eww+A3nTU5Ys0lwxKE6
            jToV+wRgbIPVDOwICvSvL4FOIsNDmk3C+o1sAxX25M5lccZtYMja65OLXW2bthjU
            ZgEJAhDTXB5bnksEixcTCfKtFebwDMIvq8L30zJutp//4dJjdidkmNZ7U1A2btRp
            svf73AJ7cDm+vUCeXl69B6pz74KdWk+1UQ5R3+BfXD8XEaEmoyCi7yH8GytW5of4
            J7tzMKA16w==
            =gGhV
            -----END PGP MESSAGE-----
          fp: 3C778F802D79787BCE9D795CE20F63D488FC275F
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
