apiVersion: v1
kind: Service
metadata:
  name: dockerhub-exporter
  labels:
    app: dockerhub-exporter
spec:
  ports:
  - port: 9888
    targetPort: {{ .Values.dockerhub.listenPort}}
    name: metrics
  selector:
    app: dockerhub-exporter