apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: circleci-exporter
  labels:
    serviceMonitorSelector: circleci-exporter
spec:
  endpoints:
  - interval: {{ .Values.circleci.interval }}
    # TODO: This is a horrible hack to allow us to scrape many projects with one exporter,
    # a better solution is to deploy one exporter per project.
    scrapeTimeout: {{ .Values.circleci.interval }}
    port: metrics
    path: {{ .Values.circleci.metricsPath }}
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      app: circleci-exporter
