apiVersion: v1
kind: Service
metadata:
  name: homebrew-exporter
  labels:
    app: homebrew-exporter
spec:
  ports:
  - port: 9888
    targetPort: {{ .Values.homebrew.listenPort}}
    name: metrics
  selector:
    app: homebrew-exporter