apiVersion: v1
kind: Service
metadata:
  name: circleci-exporter
  labels:
    app: circleci-exporter
spec:
  ports:
  - port: 9888
    targetPort: {{ .Values.circleci.listenPort}}
    name: metrics
  selector:
    app: circleci-exporter