apiVersion: v1
kind: Service
metadata:
  name: dockerhub-exporter
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: {{ .Values.dockerhub.listenPort}}
    protocol: TCP
  selector:
    app: dockerhub-exporter