apiVersion: v1
kind: Service
metadata:
  name: snapcraft-exporter
  labels:
    app: snapcraft-exporter
spec:
  ports:
  - port: 9888
    targetPort: {{ .Values.snapcraft.listenPort}}
    name: metrics
  selector:
    app: snapcraft-exporter