apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: dockerhub-exporter
  labels:
    serviceMonitorSelector: dockerhub-exporter
spec:
  endpoints:
  - interval: {{ .Values.dockerhub.interval }}
    port: metrics
    path: {{ .Values.dockerhub.metricsPath }}
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      app: dockerhub-exporter
