apiVersion: v1
kind: Service
metadata:
  name: homebrew-exporter
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: {{ .Values.homebrew.listenPort}}
    protocol: TCP
  selector:
    app: homebrew-exporter