apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: github-exporter
  labels:
    serviceMonitorSelector: github-exporter
spec:
  endpoints:
  - interval: 10m
    port: metrics
    path: {{ .Values.github.metricsPath }}
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      operated-prometheus: "true"