apiVersion: v1
kind: Service
metadata:
  name: snapcraft-exporter
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: {{ .Values.snapcraft.listenPort}}
    protocol: TCP
  selector:
    app: snapcraft-exporter