apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    serviceMonitorSelector: homebrew-exporter
    name: homebrew-exporter
spec:
  endpoints:
  - interval: 1d
    port: metrics
    path: {{ .Values.homebrew.metricsPath }}
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      operated-prometheus: "true"