apiVersion: v1
kind: Service
metadata:
  name: github-exporter
  labels:
    app: github-exporter
spec:
  ports:
  - port: 9888
    targetPort: {{ .Values.github.listenPort}}
    name: metrics
  selector:
    app: github-exporter