apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: homebrew-exporter
  labels:
    serviceMonitorSelector: homebrew-exporter
spec:
  endpoints:
  - interval: {{ .Values.homebrew.interval }}
    # Unlike the other exporters, homebrew makes a constant number of request then pulls all projects out of that request,
    # so it can scale to many projects with a single exporter and no scrapeTimeout is needed
    port: metrics
    path: {{ .Values.homebrew.metricsPath }}
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      app: homebrew-exporter
