apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: snapcraft-exporter
  labels:
    serviceMonitorSelector: snapcraft-exporter
spec:
  endpoints:
  - interval: {{ .Values.snapcraft.interval }}
    scrapeTimeout: 5m
    port: metrics
    path: {{ .Values.snapcraft.metricsPath }}
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      app: snapcraft-exporter
