apiVersion: v2
name: external-snapshotter
description: A Weaveworks Helm chart for external-snapshotter
type: application
version: 0.0.1
kubeVersion: ">=1.16.0-0"
home: https://github.com/weaveworks/profiles-catalog
sources:
  - https://github.com/filecoin-project/external-snapshotter-infra


keywords:
- external-snapshotter

annotations:
  "weave.works/profile": external-snapshotter
  "weave.works/category": client
  "weave.works/profile-ci": |
    - "gke"

maintainers:
  - name: Weaveworks
    email: support@weave.works

dependencies:
- name: flux-application
  version: "0.1.1"
  repository: "file://../flux-application"
