apiVersion: v2
name: snapshot-controller
description: A Weaveworks Helm chart for snapshot-controller
type: application
version: 0.0.1
kubeVersion: ">=1.16.0-0"
home: https://github.com/weaveworks/profiles-catalog
sources:
  - https://github.com/filecoin-project/snapshot-controller-infra


keywords:
- snapshot-controller

annotations:
  "weave.works/profile": snapshot-controller
  "weave.works/category": client
  "weave.works/profile-ci": |
    - "gke"

maintainers:
  - name: Weaveworks
    email: support@weave.works

dependencies:
- name: flux-application
  version: "0.2.0"
  repository: "file://../flux-application"
