apiVersion: v2
name: sentinel-mainnet
description: A Weaveworks Helm chart for sentinel-mainnet
type: application
version: 0.0.1
kubeVersion: ">=1.16.0-0"
home: https://github.com/weaveworks/profiles-catalog
sources:
  - https://github.com/filecoin-project/sentinel-infra


keywords:
- sentinel-mainnet

annotations:
  "weave.works/profile": sentinel-mainnet
  "weave.works/category": client
  "weave.works/profile-ci": |
    - "gke"

maintainers:
  - name: Weaveworks
    email: support@weave.works
