apiVersion: v1
data:
    PROMTAIL_PASSWORD: ENC[AES256_GCM,data:ik0IWtdk8Wp2h1hmNXBSOV7F5W870WKAG05WeIuLyInCWaRsFPbcUVBI0VY2BuiEGfSizYzzCnScaNqujyHXbpkrG6yd8tOtPuQMSdQAoOYyS3qzB2D426vrTe/S6mkt4FACiYFJx3s/MZ2K3YaILs9nBn4d0XgYD86OUgD4q4ncukOdAstuTPcfKmsEkw8h,iv:NPTNn4xzuwJsvwEGZTtJAeMfnGimzSniE2k/JEiAAAE=,tag:uz9yVHye2qkNMBcnRhw3ZQ==,type:str]
    PROMTAIL_USERNAME: ENC[AES256_GCM,data:gQQZRFmdSqI=,iv:/TPcSnxKzKbvjlLmsi8+vuXN0nnXpjaSUbfeefqrdu8=,tag:4tGjn4owNRe7VrS1k7OGrQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: promtail-auth
    namespace: flux-system
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-05-20T17:29:22Z"
    mac: ENC[AES256_GCM,data:UkVuTiSvD8OUDMZAqMOl5Kt5guFS9yRPvjgcmOZEB6QpZ6UuIwX1ReXDu/1G8sSC7+x5zB+h8ap8fPnHY0IPhtNaaDFBq4fCVUsbekq04BVILiVAu+T4Y0ziCNO4OQ+jEUU4s3f1lzX+8GGFRXDpG+/L59YV4VztJ0Q5t072cW4=,iv:lodwBAHcj8Hxi3AmJOKGPG3MX86/rVuOINB0zP1cDRA=,tag:RoL7UVpoHQIXT8giDHCKKQ==,type:str]
    pgp:
        - created_at: "2022-05-20T17:29:21Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA2IWPpjKSDN/ARAAk7BeAP+CFhEGbzYwpOt3dfYWPrXDOzPSQJAhbJ9pLdex
            GQ8sLsraxH/KI7AnASrNGo4S1PCySrtq3W9YBaUVucL51k0MMGSB6xLUMTCYyiws
            ayMn8hVLIWtsOxUQNYElsPrR5CyvBa28DMGbOQAD3DwmGhO0gJveW85Cw95iBrXb
            x/pd1g2r5gXie7YHSlEfuTvaEEcxQYlrnbcjljp4NYF5Gx/9TQOMNwqp+jnvkVnj
            LMoyKG68lWZEbQ/LS/xnhNKMmnKnYjn0Z5LsfalASiA+nGpfljHfziVX4gfQiAsj
            aVKKl1TJvfLA7P9saTl0RQKwdRVDDqJX9OZaGWROo3jGb+wlSD+2SJGBp7F8vyoz
            KZfngaPFzN5QszoMthswRZwPd3YRmpnc8AJ9emOXDiSF0Zg5oXOgzie7BnL2uiVh
            478rukMZVv3f4QLiMOBrNcOvj2YqjYLZKnZJ6qnWS2F1kcCgDpHeBTEvjrbhsSa/
            F2u6VnjjiO65i+KgRvCXK7CnGAKWrFOptqPygVkOSCuf1MAzggfQNEf4HTnnj/ys
            sUEO/O4t88qRHfPgwX0Aow0phGaosViLflAmPhEkMWWNkS+NoENXiW45BNdSHx+D
            s3zn4lie8CdBINUFHraIX6b1ploHEzdBgGyh+HLLSB2ZDT3AID1p6aYlx9chN5PU
            aAEJAhDmogI7jYjEPPllmqUAIuEDglOWNj9KLu3azT50UiP5hKFO0xhV6RCh93Ah
            QfCoAh6lg8MdHiap+1yYGz4MrNC93zpnTN+F8doLuN/1mGfTyJInuTjfNquxa7CK
            tObc5RNGiqEv
            =BsNu
            -----END PGP MESSAGE-----
          fp: 3C778F802D79787BCE9D795CE20F63D488FC275F
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
