
name: Lint and Test Charts

on: pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: 3.*

      - uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.1.0


      - name: Add helm dependencies
        shell: bash
        run: |
          for dir in $(ls -d charts/*/ | cut -f2 -d'/'); do
            repo_urls=$(helm dependency list charts/"$dir" | grep -Eo "(http|https)://[a-zA-Z0-9./?=_%:-]*" || true)
            i=0
            echo $repo_urls | while read urls; do
              for u in $urls; do
                if [ ! -z "$u" ] 
                then
                  echo $u
                  helm repo add $dir$i $u
                  ((i=i+1))
                fi
              done
            done
          done
      - name: Run chart-testing (lint)
        run: ct lint --config ct.yaml
  test-kind:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v2
          with:
            fetch-depth: 0

        - name: Set up Helm
          uses: azure/setup-helm@v1
          with:
            version: 3.*

        - uses: actions/setup-python@v2
          with:
            python-version: 3.7

        - name: Set up chart-testing
          uses: helm/chart-testing-action@v2.1.0

        - name: Adding platforms
          run: |
            touch /tmp/platforms
            echo kind >> /tmp/platforms

        - name: Compile and Sort layers alphabetically
          id: compile-and-sort-layers
          run: |
            make -f makefiles/Makefile sort-layers

        - name: Add helm dependencies
          shell: bash
          run: |
            for dir in $(ls -d charts/*/ | cut -f2 -d'/'); do
              repo_urls=$(helm dependency list charts/"$dir" | grep -Eo "(http|https)://[a-zA-Z0-9./?=_%:-]*" || true)
              i=0
              echo $repo_urls | while read urls; do
                for u in $urls; do
                  if [ ! -z "$u" ] 
                  then
                    echo $u
                    helm repo add $dir$i $u
                    ((i=i+1))
                  fi
                done
              done
            done

        - name: Create kind cluster
          if: steps.compile-and-sort-layers.outputs.kind-ci == 'true'
          uses: helm/kind-action@v1.2.0

        - name: Create wego-system namespace (kind)
          if: steps.compile-and-sort-layers.outputs.kind-ci == 'true' 
          run: kubectl create namespace wego-system

        - name: Test kind platform (kind)
          if: steps.compile-and-sort-layers.outputs.kind-ci == 'true' 
          env:
            INFRASTRUCTURE: "kind"
          run:  make -f makefiles/Makefile test