{{- if .Values.logzioCert }}
---
apiVersion: {{ .Values.apiVersions.configMap }}
kind: ConfigMap
metadata:
  name: logzio-logs-cert
  namespace: {{ .Release.Namespace }}
  labels:
    k8s-app: filebeat
data:
{{- range $path, $config := .Values.logzioCert }}
  {{ $path }}: |-
{{ $config | indent 4 -}}
{{- end -}}
{{- end -}}

{{- if .Values.filebeatConfig }}
---
apiVersion: {{ .Values.apiVersions.configMap }}
kind: ConfigMap
metadata:
  name: filebeat-config
  namespace: {{ .Release.Namespace }}
  labels:
    k8s-app: filebeat
data:
{{- if eq .Values.configType "standard" }}
{{- range $path, $config := .Values.filebeatConfig.standardConfig }}
  {{ $path }}: |-
{{ $config | indent 4 -}}
{{- end -}}
{{- else if eq .Values.configType "autodiscover" }}
{{- range $path, $config := .Values.filebeatConfig.autodiscoverConfig }}
  {{ $path }}: |-
{{ $config | indent 4 -}}
{{- end -}}
{{- else if eq .Values.configType "auto-custom" }}
{{- range $path, $config := fromYaml .Values.filebeatConfig.autoCustomConfig }}
  {{ $path }}: |-
{{ $config | indent 4 -}}
{{- end -}}
{{- end -}}
{{- end -}}

{{- if .Values.winlogbeatConfig }}
---
apiVersion: {{ .Values.apiVersions.configMap }}
kind: ConfigMap
metadata:
  name: winlogbeat-config
  namespace: {{ .Release.Namespace }}
  labels:
    k8s-app: filebeat
data:
{{- if eq .Values.winlogbeatConfigType "standard" }}
{{- range $path, $config := .Values.winlogbeatConfig.standardConfig }}
  {{ $path }}: |-
{{ $config | indent 4 -}}
{{- end -}}
{{- end -}}
{{- end -}}

{{- if .Values.filebeatWindowsConfig }}
---
apiVersion: {{ .Values.apiVersions.configMap }}
kind: ConfigMap
metadata:
  name: filebeat-windows-config
  namespace: {{ .Release.Namespace }}
  labels:
    k8s-app: filebeat
data:
{{- if eq .Values.filebeatWindowsConfigType "standard" }}
{{- range $path, $config := .Values.filebeatWindowsConfig.standardConfig }}
  {{ $path }}: |-
{{ $config | indent 4 -}}
{{- end -}}
{{- else if eq .Values.filebeatWindowsConfigType "autodiscover" }}
{{- range $path, $config := .Values.filebeatWindowsConfig.autodiscoverConfig }}
  {{ $path }}: |-
{{ $config | indent 4 -}}
{{- end -}}
{{- else if eq .Values.filebeatWindowsConfigType "auto-custom" }}
{{- range $path, $config := fromYaml .Values.filebeatWindowsConfig.autoCustomConfig }}
  {{ $path }}: |-
{{ $config | indent 4 -}}
{{- end -}}
{{- end -}}
{{- end -}}